insert into OBSERVATION_FACT select o.ENCOUNTER_NUM   ,  o.PATIENT_NUM   ,  replace(o.CONCEPT_CD, 'ICD9:', 'ICD9CM:') as concept_cd  ,   o.PROVIDER_ID    ,      o.START_DATE    ,   o.MODIFIER_CD    , o.INSTANCE_NUM  ,   o.VALTYPE_CD  ,   o.TVAL_CHAR  ,   o.NVAL_NUM   ,  o.VALUEFLAG_CD ,    o.QUANTITY_NUM   ,  o.UNITS_CD   ,  o.END_DATE           ,     o.LOCATION_CD   ,  o.OBSERVATION_BLOB  ,   o.CONFIDENCE_NUM  ,  o.UPDATE_DATE     ,       o.DOWNLOAD_DATE    ,     o.IMPORT_DATE      ,      o.SOURCESYSTEM_CD  ,   o.UPLOAD_ID   from observation_fact o, concept_dimension c where o.CONCEPT_CD = c.CONCEPT_CD and c.CONCEPT_PATH like '\i2b2\Diagnoses\%';
insert into OBSERVATION_FACT select  o.ENCOUNTER_NUM   ,  o.PATIENT_NUM   ,  replace(o.CONCEPT_CD, 'ICD9:', 'ICD9PROC:') as concept_cd  ,   o.PROVIDER_ID    ,      o.START_DATE    ,    o.MODIFIER_CD    , o.INSTANCE_NUM  ,   o.VALTYPE_CD  ,   o.TVAL_CHAR  ,   o.NVAL_NUM   ,  o.VALUEFLAG_CD ,    o.QUANTITY_NUM   ,  o.UNITS_CD   ,  o.END_DATE           ,    o.LOCATION_CD   ,  o.OBSERVATION_BLOB  ,   o.CONFIDENCE_NUM  ,  o.UPDATE_DATE     ,       o.DOWNLOAD_DATE    ,     o.IMPORT_DATE      ,      o.SOURCESYSTEM_CD  ,   o.UPLOAD_ID    from observation_fact o, concept_dimension c where o.CONCEPT_CD = c.CONCEPT_CD and c.CONCEPT_PATH like '\i2b2\Procedures\%';
update ncats_demographics set c_facttablecolumn = 'patient_num', c_tablename = 'patient_dimension', c_columnname = 'vital_status_cd', c_operator = 'IN' , c_dimcode = '''Y'',''D''' where c_fullname like '\ACT\Demographics\Vital Status\Known Deceased\%';
update ncats_demographics set c_facttablecolumn = 'patient_num', c_tablename = 'patient_dimension', c_columnname = 'sex_cd', c_operator = '=' , c_dimcode = 'F' where c_fullname like '\ACT\Demographics\Sex\Female\%';
update ncats_demographics set c_facttablecolumn = 'patient_num', c_tablename = 'patient_dimension', c_columnname = 'sex_cd', c_operator = '=' , c_dimcode = 'M' where c_fullname like '\ACT\Demographics\Sex\Male\%';
update ncats_demographics set c_facttablecolumn = 'patient_num', c_tablename = 'patient_dimension', c_columnname = 'race_cd', c_operator = 'IN' , c_dimcode = '''black'',''african american''' where c_fullname like '\ACT\Demographics\Race\Black or African American\%';
update ncats_demographics set c_facttablecolumn = 'patient_num', c_tablename = 'patient_dimension', c_columnname = 'race_cd', c_operator = 'IN' , c_dimcode = '''white''' where c_fullname like '\ACT\Demographics\Race\White\%';
update ncats_demographics set c_facttablecolumn = 'patient_num', c_tablename = 'patient_dimension', c_columnname = 'race_cd', c_operator = 'IN' , c_dimcode = '''indian''' where c_fullname like '\ACT\Demographics\Race\American Indian or Alaska Native\%';
update ncats_demographics set c_facttablecolumn = 'patient_num', c_tablename = 'patient_dimension', c_columnname = 'race_cd', c_operator = 'IN' , c_dimcode = '''asian''' where c_fullname like '\ACT\Demographics\Race\Asian\%';
