CREATE OR REPLACE FILE FORMAT CSV_FORMAT
            TYPE=CSV
            FIELD_DELIMITER = '\t'
            ESCAPE=NONE
            NULL_IF = ('NULL')
            COMPRESSION=AUTO
            ESCAPE_UNENCLOSED_FIELD=NONE
            FIELD_OPTIONALLY_ENCLOSED_BY='"'
            SKIP_HEADER=0;


CREATE OR REPLACE STAGE CSV_STAGE FILE_FORMAT = CSV_FORMAT;

PUT file:///opt/airflow/SCRIPTS/DATA_INSTALLER/i2b2-data/edu.harvard.i2b2.data/Release_1-8/NewInstall/Metadata/act/scripts/snowflake/*.csv.gz @CSV_STAGE PARALLEL=4 AUTO_COMPRESS=TRUE SOURCE_COMPRESSION=AUTO_DETECT OVERWRITE=TRUE;


COPY INTO SCHEMES FROM @CSV_STAGE/SCHEMES.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO TABLE_ACCESS FROM @CSV_STAGE/TABLE_ACCESS.csv FILE_FORMAT=CSV_FORMAT;

--TODO: implement stored procedure to load the data
COPY INTO  ACT_COVID_V41 FROM @CSV_STAGE/ACT_COVID_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_CPT4_PX_V41 FROM @CSV_STAGE/ACT_CPT4_PX_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_DEM_V41 FROM @CSV_STAGE/ACT_DEM_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_HCPCS_PX_V41 FROM @CSV_STAGE/ACT_HCPCS_PX_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_ICD10CM_DX_V41 FROM @CSV_STAGE/ACT_ICD10CM_DX_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_ICD10PCS_PX_V41 FROM @CSV_STAGE/ACT_ICD10PCS_PX_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_ICD10_ICD9_DX_V4 FROM @CSV_STAGE/ACT_ICD10_ICD9_DX_V4.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_ICD9CM_DX_V4 FROM @CSV_STAGE/ACT_ICD9CM_DX_V4.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_ICD9CM_PX_V4 FROM @CSV_STAGE/ACT_ICD9CM_PX_V4.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_LOINC_LAB_PROV_V41 FROM @CSV_STAGE/ACT_LOINC_LAB_PROV_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_LOINC_LAB_V4 FROM @CSV_STAGE/ACT_LOINC_LAB_V4.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_MED_ALPHA_V41 FROM @CSV_STAGE/ACT_MED_ALPHA_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_MED_VA_V41 FROM @CSV_STAGE/ACT_MED_VA_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_RESEARCH_V41 FROM @CSV_STAGE/ACT_RESEARCH_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_SDOH_V41 FROM @CSV_STAGE/ACT_SDOH_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_VAX_V41 FROM @CSV_STAGE/ACT_VAX_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_VISIT_DETAILS_V41 FROM @CSV_STAGE/ACT_VISIT_DETAILS_V41.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_VITAL_SIGNS_V4 FROM @CSV_STAGE/ACT_VITAL_SIGNS_V4.csv FILE_FORMAT=CSV_FORMAT;
COPY INTO ACT_ZIPCODE_V41 FROM @CSV_STAGE/ACT_ZIPCODE_V41.csv FILE_FORMAT=CSV_FORMAT;