CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
    TYPE = PARQUET
    COMPRESSION = SNAPPY
    ;
CREATE OR REPLACE STAGE PARQUET_STAGE FILE_FORMAT = PARQUET_FORMAT;
PUT file://${basedir}/act/scripts/snowflake/*.snappy.parquet @PARQUET_STAGE PARALLEL=4 AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
COPY INTO SCHEMES FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*SCHEMES.*\\.parquet';
COPY INTO TABLE_ACCESS FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*TABLE_ACCESS.*\\.parquet';
COPY INTO ACT_COVID_V41 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_COVID_V41.*\\.parquet';
COPY INTO ACT_CPT4_PX_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_CPT4_PX_V42.*\\.parquet';
COPY INTO ACT_DEM_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_DEM_V42.*\\.parquet';
COPY INTO ACT_HCPCS_PX_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_HCPCS_PX_V42.*\\.parquet';
COPY INTO ACT_ICD10CM_DX_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_ICD10CM_DX_V42.*\\.parquet';
COPY INTO ACT_ICD10PCS_PX_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_ICD10PCS_PX_V42.*\\.parquet';
COPY INTO ACT_ICD10_ICD9_DX_V4 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_ICD10_ICD9_DX_V4.*\\.parquet';
COPY INTO ACT_ICD9CM_DX_V4 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_ICD9CM_DX_V4.*\\.parquet';
COPY INTO ACT_ICD9CM_PX_V4 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_ICD9CM_PX_V4.*\\.parquet';
COPY INTO ACT_LOINC_LAB_PROV_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_LOINC_LAB_PROV_V42.*\\.parquet';
COPY INTO ACT_LOINC_LAB_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_LOINC_LAB_V42.*\\.parquet';
COPY INTO ACT_MED_ALPHA_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_MED_ALPHA_V42.*\\.parquet';
COPY INTO ACT_MED_VA_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_MED_VA_V42.*\\.parquet';
COPY INTO ACT_RESEARCH_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_RESEARCH_V42.*\\.parquet';
COPY INTO ACT_SDOH_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_SDOH_V42.*\\.parquet';
COPY INTO ACT_VAX_V42 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_VAX_V42.*\\.parquet';
COPY INTO ACT_VISIT_DETAILS_V41 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_VISIT_DETAILS_V41.*\\.parquet';
COPY INTO ACT_VITAL_SIGNS_V4 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_VITAL_SIGNS_V4.*\\.parquet';
COPY INTO ACT_ZIPCODE_V41 FROM @PARQUET_STAGE/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT PATTERN = '.*ACT_ZIPCODE_V41.*\\.parquet';