insert into QT_BREAKDOWN_PATH(NAME,VALUE,CREATE_DATE) values ('PATIENT_GENDER_COUNT_XML','\\i2b2_DEMO\i2b2\Demographics\Gender\',getdate())
insert into QT_BREAKDOWN_PATH(NAME,VALUE,CREATE_DATE) values ('PATIENT_RACE_COUNT_XML','\\i2b2_DEMO\i2b2\Demographics\Race\',getdate())
insert into QT_BREAKDOWN_PATH(NAME,VALUE,CREATE_DATE) values ('PATIENT_VITALSTATUS_COUNT_XML','\\i2b2_DEMO\i2b2\Demographics\Vital Status\',getdate())
insert into QT_BREAKDOWN_PATH(NAME,VALUE,CREATE_DATE) values ('PATIENT_AGE_COUNT_XML','\\i2b2_DEMO\i2b2\Demographics\Age\',getdate())
insert into qt_breakdown_path (name, value, create_date) values ('PATIENT_LOS_XML','select length_of_stay as patient_range, count(distinct a.PATIENT_num) as patient_count from {{{DATABASE_NAME}}}.visit_dimension a, {{{DATABASE_NAME}}}.#DX b where a.patient_num = b.patient_num group by a.length_of_stay order by 1', GETDATE());
insert into qt_breakdown_path (name, value, create_date) values ('PATIENT_TOP20MEDS_XML','select top 20 b.name_char as patient_range, count(distinct a.patient_num) as patient_count from {{{DATABASE_NAME}}}.observation_fact a, {{{DATABASE_NAME}}}.concept_dimension b, {{{DATABASE_NAME}}}.#DX c where a.concept_cd = b.concept_cd and concept_path like ''\i2b2\Medications\%'' and a.patient_num = c.patient_num   group by name_char order by patient_count desc', GETDATE());
insert into qt_breakdown_path (name, value, create_date) values ('PATIENT_TOP20DIAG_XML','select top 20 b.name_char as patient_range, count(distinct a.patient_num) as patient_count from {{{DATABASE_NAME}}}.observation_fact a, {{{DATABASE_NAME}}}.concept_dimension b, {{{DATABASE_NAME}}}.#DX c where a.concept_cd = b.concept_cd and concept_path like ''\i2b2\Diagnoses\%'' and a.patient_num = c.patient_num   group by name_char order by patient_count desc', GETDATE());
insert into qt_breakdown_path (name, value, create_date) values ('PATIENT_INOUT_XML','select INOUT_CD as patient_range, count(distinct a.patient_num) as patient_count from {{{DATABASE_NAME}}}.visit_dimension a, {{{DATABASE_NAME}}}.#DX b where a.patient_num = b.patient_num group by a.INOUT_CD order by 1', GETDATE());
insert into qt_breakdown_path (name, value, create_date) values ('ADMIN_RUNNING_QUERY_XML','select a.name + '' '' + format(b.start_date, ''yyyy-MM-dd'')  as patient_range, b.batch_mode as patient_count from qt_query_master a, QT_QUERY_INSTANCE b where a.QUERY_MASTER_ID = b.QUERY_MASTER_ID and create_date >=  DATEADD(day,-7, GETDATE())   and b.END_DATE is null order by b.BATCH_MODE, a.name',GETDATE());
insert into qt_breakdown_path (name, value, create_date) values ('ADMIN_QUERY_TIME_XML','select format(create_date, ''HH'') as patient_range, count(create_date) as patient_count from qt_query_master where delete_date is null GROUP BY   format(create_date, ''HH'')',GETDATE());
insert into qt_breakdown_path (name, value, create_date) values ('ADMIN_QUERY_BY_USER_XML','select user_id as patient_range, count(user_id)  as patient_count from qt_query_master where create_date >=   DATEADD(month,-1, GETDATE())   and delete_date is null group by user_id order by user_id',GETDATE());
insert into qt_breakdown_path (name, value, create_date) values ('ADMIN_RUN_QUERY_XML','select format(create_date, ''MM'') as patient_range, count(create_date) as patient_count from qt_query_master where create_date >= DATEADD(month,-12, GETDATE())  and delete_date is null GROUP BY format(create_date, ''MM'')',GETDATE());

