INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('NDC:','NDC','National Drug Code');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DSG-NLP:','DSG-NLP','Natural Language Processing Data');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('UMLS:','UMLS','United Medical Language System');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('ICD9CM:','ICD9CM','ICD9 code for diagnoses and procedures');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('ICD10CM:','ICD10CM','ICD10 code for diagnoses');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('LOINC:','LOINC','Lab codes');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|AGE:','DEM|AGE','Age of patient from demographics data');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|DATE:','DEM|DATE','Patient date of birth from demographics data');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|MARITAL:','DEM|MARITAL','Marital Status of patient');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|LANGUAGE:','DEM|LANGUAGE','Primary language spoken by patient');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|RACE:','DEM|RACE','Race of patient');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|RELIGION:','DEM|RELIGION','Religion of patient');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|SEX:','DEM|SEX','Gender of patient');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|VITAL STATUS:','DEM|VITAL STATUS','Vital status of patient');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|ZIPCODE:','DEM|ZIPCODE',null);
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('(null)','None','No scheme');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('RXNORM:','RXNORM','RxNorm');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('DEM|HISP:','DEM|HISP','Hispanic origins');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('NUI:','NDF-RT','NDF-RT VA Drug Classification');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('ICD9PROC:','ICD9PROC','ICD9 code for procedures');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('ICD10PCS:','ICD10PCS','ICD10 code for procedures');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('CPT4:','CPT4','Current Procedural Terminology');
INSERT into SCHEMES (C_KEY,C_NAME,C_DESCRIPTION) values ('HCPCS:','HCPCS','Healthcare Common Procedure Coding System');
