# Database setup parameters
db.type=sqlserver
db.username=USER_NAME
db.password=PWD
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost:1433;database=DB_NAME
db.project=demo
