-- 1. i2b2metadata
CREATE USER i2b2metadata IDENTIFIED BY demouser;
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE ROLE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW TO i2b2metadata;
GRANT UNLIMITED TABLESPACE TO i2b2metadata;

-- 2. i2b2demodata
CREATE USER i2b2demodata IDENTIFIED BY demouser;
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE ROLE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW TO i2b2demodata;
GRANT UNLIMITED TABLESPACE TO i2b2demodata;

-- 3. i2b2hive
CREATE USER i2b2hive IDENTIFIED BY demouser;
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE ROLE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW TO i2b2hive;
GRANT UNLIMITED TABLESPACE TO i2b2hive;

-- 4. i2b2imdata
CREATE USER i2b2imdata IDENTIFIED BY demouser;
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE ROLE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW TO i2b2imdata;
GRANT UNLIMITED TABLESPACE TO i2b2imdata;

-- 5. i2b2pm
CREATE USER i2b2pm IDENTIFIED BY demouser;
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE ROLE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW TO i2b2pm;
GRANT UNLIMITED TABLESPACE TO i2b2pm;

-- 6. i2b2workdata
CREATE USER i2b2workdata IDENTIFIED BY demouser;
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE ROLE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW TO i2b2workdata;
GRANT UNLIMITED TABLESPACE TO i2b2workdata;

-- Prevent password expiration (matches "Expire Password is NOT checked")
-- ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
