INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\21\', '21', 'N', 'LA ', NULL, 'birn:mmse21', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\21\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease \ 21', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Education\College grad.\', 'College grad.', 'N', 'LA ', NULL, 'birn:edu4', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Education\College grad.\', NULL, 'oasis \ Demographics \ Education \ College grad.', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\27\', '27', 'N', 'LA ', NULL, 'birn:mmse27', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\27\', NULL, 'oasis \ Clinical Measures \ MMSE score \ No Alzheimer''s disease \ 27', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\28\', '28', 'N', 'LA ', NULL, 'birn:mmse28', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\28\', NULL, 'oasis \ Clinical Measures \ MMSE score \ No Alzheimer''s disease \ 28', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\29\', '29', 'N', 'LA ', NULL, 'birn:mmse29', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\29\', NULL, 'oasis \ Clinical Measures \ MMSE score \ No Alzheimer''s disease \ 29', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\30\', '30', 'N', 'LA ', NULL, 'birn:mmse30', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\30\', NULL, 'oasis \ Clinical Measures \ MMSE score \ No Alzheimer''s disease \ 30', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\', 'Clinical Dementia Rating (CDR)', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\', NULL, 'oasis \ Clinical Measures \ Clinical Dementia Rating (CDR)', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\nondemented\', 'nondemented', 'N', 'LA ', NULL, 'birn:cdr0', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\nondemented\', NULL, 'oasis \ Clinical Measures \ MMSE score \ nondemented', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\very mild dementia\', 'very mild dementia', 'N', 'LA ', NULL, 'birn:cdr05', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\very mild dementia\', NULL, 'oasis \ Clinical Measures \ Clinical Dementia Rating (CDR) \ very mild dementia', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\mild dementia\', 'mild dementia', 'N', 'LA ', NULL, 'birn:cdr1', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\mild dementia\', NULL, 'oasis \ Clinical Measures \ Clinical Dementia Rating (CDR) \ mild dementia', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\moderate dementia\', 'moderate dementia', 'N', 'LA ', NULL, 'birn:cdr2', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\Clinical Dementia Rating (CDR)\moderate dementia\', NULL, 'oasis \ Clinical Measures \ Clinical Dementia Rating (CDR) \ moderate dementia', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Hand Orientation\Left Handed\', 'Left Handed', 'N', 'LA ', NULL, 'birn:handl', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Hand Orientation\Left Handed\', NULL, 'oasis \ Demographics \ Hand Orientation \ Left Handed', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(2, '\BIRN\oasis\Demographics\', 'Demographics', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\', NULL, 'oasis \ Demographics', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(2, '\BIRN\oasis\Derived Anatomic Volumes\', 'Derived Anatomic Volumes', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Derived Anatomic Volumes\', NULL, 'oasis \ Derived Anatomic Volumes', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(2, '\BIRN\oasis\Clinical Measures\', 'Clinical Measures', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\', NULL, 'oasis \ Clinical Measures', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Derived Anatomic Volumes\Estimated Total Intracranial Volume\', 'Est. Total Intracranial Volume', 'N', 'LA ', NULL, 'birn:etiv', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Derived Anatomic Volumes\Estimated Total Intracranial Volume\', NULL, 'oasis \ Derived Anatomic Volumes \ Est. Total Intracranial Volume', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\', 'Mild Alzheimers disease', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\14\', '14', 'N', 'LA ', NULL, 'birn:mmse14', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\14\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease \ 14', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\24\', '24', 'N', 'LA ', NULL, 'birn:mmse24', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\24\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease \ 24', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(0, '\BIRN\', 'BIRN', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\', NULL, 'BIRN', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(1, '\BIRN\oasis\', 'Oasis', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\', NULL, 'oasis', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Demographics\Hand Orientation\', 'Hand Orientation', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Hand Orientation\', NULL, 'oasis \ Demographics \ Hand Orientation', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Hand Orientation\Right Handed\', 'Right Handed', 'N', 'LA ', NULL, 'birn:handr', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Hand Orientation\Right Handed\', NULL, 'oasis \ Demographics \ Hand Orientation \ Right Handed', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Demographics\Education\', 'Education', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Education\', NULL, 'oasis \ Demographics \ Education', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Education\Less than high school grad.\', 'Less than high school grad.', 'N', 'LA ', NULL, 'birn:edu1', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Education\Less than high school grad.\', NULL, 'oasis \ Demographics \ Education \ Less than high school grad.', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Education\High school grad.\', 'High school grad.', 'N', 'LA ', NULL, 'birn:edu2', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Education\High school grad.\', NULL, 'oasis \ Demographics \ Education \ High school grad.', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Education\Some college\', 'Some college', 'N', 'LA ', NULL, 'birn:edu3', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Education\Some college\', NULL, 'oasis \ Demographics \ Education \ Some college', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Education\Beyond college\', 'Beyond college', 'N', 'LA ', NULL, 'birn:edu5', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Education\Beyond college\', NULL, 'oasis \ Demographics \ Education \ Beyond college', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Demographics\Socioeconomic Status\', 'Socioeconomic Status', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Socioeconomic Status\', NULL, 'oasis \ Demographics \ Socioeconomic Status', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Socioeconomic Status\Status 1\', 'Status 1', 'N', 'LA ', NULL, 'birn:ses1', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Socioeconomic Status\Status 1\', NULL, 'oasis \ Demographics \ Socioeconomic Status \ Status 1', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Socioeconomic Status\Status 2\', 'Status 2', 'N', 'LA ', NULL, 'birn:ses2', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Socioeconomic Status\Status 2\', NULL, 'oasis \ Demographics \ Socioeconomic Status \ Status 2', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Socioeconomic Status\Status 3\', 'Status 3', 'N', 'LA ', NULL, 'birn:ses3', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Socioeconomic Status\Status 3\', NULL, 'oasis \ Demographics \ Socioeconomic Status \ Status 3', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Socioeconomic Status\Status 4\', 'Status 4', 'N', 'LA ', NULL, 'birn:ses4', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Socioeconomic Status\Status 4\', NULL, 'oasis \ Demographics \ Socioeconomic Status \ Status 4', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Demographics\Socioeconomic Status\Status 5\', 'Status 5', 'N', 'LA ', NULL, 'birn:ses5', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Demographics\Socioeconomic Status\Status 5\', NULL, 'oasis \ Demographics \ Socioeconomic Status \ Status 5', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Clinical Measures\MMSE score\', 'MMSE score', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\', NULL, 'oasis \ Clinical Measures \ MMSE score', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\', 'Moderate Alzheimers disease', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\13\', '13', 'N', 'LA ', NULL, 'birn:mmse13', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\13\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease \ 13', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\15\', '15', 'N', 'LA ', NULL, 'birn:mmse15', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\15\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease \ 15', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\16\', '16', 'N', 'LA ', NULL, 'birn:mmse16', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\16\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease \ 16', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\17\', '17', 'N', 'LA ', NULL, 'birn:mmse17', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\17\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease \ 17', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\18\', '18', 'N', 'LA ', NULL, 'birn:mmse18', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\18\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease \ 18', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\19\', '19', 'N', 'LA ', NULL, 'birn:mmse19', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Moderate Alzheimers disease\19\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Moderate Alzheimer''s disease \ 19', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\20\', '20', 'N', 'LA ', NULL, 'birn:mmse20', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\20\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease \ 20', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\22\', '22', 'N', 'LA ', NULL, 'birn:mmse22', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\22\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease \ 22', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\23\', '23', 'N', 'LA ', NULL, 'birn:mmse23', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\23\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease \ 23', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\25\', '25', 'N', 'LA ', NULL, 'birn:mmse25', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\25\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease \ 25', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\26\', '26', 'N', 'LA ', NULL, 'birn:mmse26', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\Mild Alzheimers disease\26\', NULL, 'oasis \ Clinical Measures \ MMSE score \ Mild Alzheimer''s disease \ 26', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\', 'No Alzheimers disease', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Clinical Measures\MMSE score\No Alzheimers disease\', NULL, 'oasis \ Clinical Measures \ MMSE score \ No Alzheimer''s disease', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(2, '\BIRN\oasis\Images\', 'Images', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\', NULL, 'oasis \ Images', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Derived Anatomic Volumes\Normalized Whole Brain Volume\', 'Normalized Whole Brain Volume', 'N', 'LA ', NULL, 'birn:nwbv', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Derived Anatomic Volumes\Normalized Whole Brain Volume\', NULL, 'oasis \ Derived Anatomic Volumes \ Normalized Whole Brain Volume', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Derived Anatomic Volumes\Atlas scaling factor\', 'Atlas scaling factor', 'N', 'LA ', NULL, 'birn:asf', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Derived Anatomic Volumes\Atlas scaling factor\', NULL, 'oasis \ Derived Anatomic Volumes \ Atlas scaling factor', '@', '20071010 17:10:01.0', '20071010 17:10:28.0', '20071010 17:10:36.0', 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Images\Raw Images\', 'Raw Images', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\', NULL, 'oasis \ Images \ Raw Images', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Images\Averaged Images\', 'Averaged Images', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Averaged Images\', NULL, 'oasis \ Images \ Averaged Images', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Images\Atlas Registered\', 'Atlas Registered', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Atlas Registered\', NULL, 'oasis \ Images \ Atlas Registered Images', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Images\Masked Atlas\', 'Masked Atlas', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Masked Atlas\', NULL, 'oasis \ Images \ Masked Atlas Images', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(3, '\BIRN\oasis\Images\Gray/White Segmented\', 'Gray/White Segmented', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Gray/White Segmented\', NULL, 'oasis \ Images \ Gray/White Segmented', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', NULL);
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Gray/White Segmented\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:gwseg_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Gray/White Segmented\Transverse\', NULL, 'oasis \ Images \ Gray/White Segmented \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Gray/White Segmented\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:gwseg_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Gray/White Segmented\Coronal\', NULL, 'oasis \ Images \ Gray/White Segmented \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Gray/White Segmented\Sagittal\', 'Sagittal', 'N', 'LI ', NULL, 'birn:gwseg_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Gray/White Segmented\Sagittal\', NULL, 'oasis \ Images \ Gray/White Segmented \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Masked Atlas\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:maskat_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Masked Atlas\Transverse\', NULL, 'oasis \ Images \ Masked Atlas \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Masked Atlas\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:maskat_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Masked Atlas\Coronal\', NULL, 'oasis \ Images \ Masked Atlas \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Masked Atlas\Sagittal\', 'Sagittal', 'N', 'LI ', NULL, 'birn:maskat_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Masked Atlas\Sagittal\', NULL, 'oasis \ Images \ Masked Atlas \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Atlas Registered\Sagittal\', 'Sagittal', 'N', 'LI ', NULL, 'birn:atlas_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Atlas Registered\Sagittal\', NULL, 'oasis \ Images \ Atlas Registered \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Atlas Registered\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:atlas_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Atlas Registered\Coronal\', NULL, 'oasis \ Images \ Atlas Registered \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Atlas Registered\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:atlas_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Atlas Registered\Transverse\', NULL, 'oasis \ Images \ Atlas Registered \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Averaged Images\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:avg_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Averaged Images\Transverse\', NULL, 'oasis \ Images \ Averaged Images \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Averaged Images\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:avg_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Averaged Images\Coronal\', NULL, 'oasis \ Images \ Averaged Images \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Averaged Images\Sagittal\', 'Sagittal', 'N', 'LI ', NULL, 'birn:avg_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Averaged Images\Sagittal\', NULL, 'oasis \ Images \ Averaged Images \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Raw Images\Third Sample\', 'Third Sample', 'N', 'FA ', NULL, 'birn:image3', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Third Sample\', NULL, 'oasis \ Images \ Raw Images \ Third Sample', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Raw Images\Fourth Sample\', 'Fourth Sample', 'N', 'FA ', NULL, 'birn:image4', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Fourth Sample\', NULL, 'oasis \ Images \ Raw Images \ Fourth Sample', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Raw Images\First Sample\', 'First Sample', 'N', 'FA ', NULL, 'birn:image1', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\First Sample\', NULL, 'oasis \ Images \ Raw Images \ First Sample', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(4, '\BIRN\oasis\Images\Raw Images\Second Sample\', 'Second Sample', 'N', 'FA ', NULL, 'birn:image2', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Second Sample\', NULL, 'oasis \ Images \ Raw Images \ Second Sample', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\First Sample\Sagittal\', 'Sagittal', 'N', 'LA ', NULL, 'birn:image1_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\First Sample\Sagittal\', NULL, 'oasis \ Images \ Raw Images \ First Sample \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\First Sample\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:image1_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\First Sample\Coronal\', NULL, 'oasis \ Images \ Raw Images \ First Sample \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\First Sample\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:image1_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\First Sample\Transverse\', NULL, 'oasis \ Images \ Raw Images \ First Sample \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Second Sample\Sagittal\', 'Sagittal', 'N', 'LA ', NULL, 'birn:image2_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Second Sample\Sagittal\', NULL, 'oasis \ Images \ Raw Images \ Second Sample \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Second Sample\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:image2_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Second Sample\Coronal\', NULL, 'oasis \ Images \ Raw Images \ Second Sample \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Second Sample\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:image2_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Second Sample\Transverse\', NULL, 'oasis \ Images \ Raw Images \ Second Sample \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Third Sample\Sagittal\', 'Sagittal', 'N', 'LA ', NULL, 'birn:image3_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Third Sample\Sagittal\', NULL, 'oasis \ Images \ Raw Images \ Third Sample \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Third Sample\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:image3_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Third Sample\Coronal\', NULL, 'oasis \ Images \ Raw Images \ Third Sample \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Third Sample\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:image3_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Third Sample\Transverse\', NULL, 'oasis \ Images \ Raw Images \ Third Sample \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Fourth Sample\Sagittal\', 'Sagittal', 'N', 'LA ', NULL, 'birn:image4_sag', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Fourth Sample\Sagittal\', NULL, 'oasis \ Images \ Raw Images \ Fourth Sample \ Sagittal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Fourth Sample\Coronal\', 'Coronal', 'N', 'LI ', NULL, 'birn:image4_coronal', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Fourth Sample\Coronal\', NULL, 'oasis \ Images \ Raw Images \ Third Sample \ Coronal', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
INSERT INTO BIRN(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD)
  VALUES(5, '\BIRN\oasis\Images\Raw Images\Fourth Sample\Transverse\', 'Transverse', 'N', 'LI ', NULL, 'birn:image4_trans', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\BIRN\oasis\Images\Raw Images\Fourth Sample\Transverse\', NULL, 'oasis \ Images \ Raw Images \ Fourth Sample \ Transverse', '@', '20071010 17:10:01.0', NULL, NULL, 'OASIS', 'IMG');
