CREATE OR REPLACE FILE FORMAT CSV_FORMAT
            TYPE=CSV
            FIELD_DELIMITER = '\t'
            ESCAPE=NONE
            NULL_IF = ('NULL')
            COMPRESSION=AUTO
            ESCAPE_UNENCLOSED_FIELD=NONE
            FIELD_OPTIONALLY_ENCLOSED_BY='"'
            SKIP_HEADER=0;


CREATE OR REPLACE STAGE CSV_STAGE FILE_FORMAT = CSV_FORMAT;

PUT file:///opt/airflow/SCRIPTS/DATA_INSTALLER/i2b2-data/edu.harvard.i2b2.data/Release_1-8/NewInstall/Crcdata/act/scripts/snowflake/*.csv.gz @CSV_STAGE PARALLEL=4 AUTO_COMPRESS=TRUE SOURCE_COMPRESSION=AUTO_DETECT OVERWRITE=TRUE;


COPY INTO CONCEPT_DIMENSION FROM @CSV_STAGE/CONCEPT_DIMENSION.csv FILE_FORMAT=CSV_FORMAT ;