CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
    TYPE = PARQUET
    COMPRESSION = SNAPPY;
CREATE OR REPLACE STAGE PARQUET_STAGE FILE_FORMAT = PARQUET_FORMAT;
PUT file://${basedir}/act/scripts/snowflake/*.snappy.parquet @PARQUET_STAGE PARALLEL=4 AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
COPY INTO CONCEPT_DIMENSION FROM @PARQUET_STAGE/CONCEPT_DIMENSION MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FORMAT;