
 --------------------------------------------------------
--  DDL for Table ONT_DB_LOOKUP
--------------------------------------------------------
 
 CREATE TABLE ONT_DB_LOOKUP ( 
	"C_DOMAIN_ID"   	VARCHAR2(255)   NOT NULL,
	"C_PROJECT_PATH" 	VARCHAR2(255)   NOT NULL, 
	"C_OWNER_ID"     	VARCHAR2(255)   NOT NULL, 
	"C_DB_FULLSCHEMA"   VARCHAR2(255)   NOT NULL, 
	"C_DB_DATASOURCE"	VARCHAR2(255)   NOT NULL, 
	"C_DB_SERVERTYPE"	VARCHAR2(255)   NOT NULL, 
	"C_DB_NICENAME"  	VARCHAR2(255)   NULL,
	"C_DB_TOOLTIP"   	VARCHAR2(255)   NULL, 
	"C_COMMENT"      	CLOB   NULL,
	"C_ENTRY_DATE"   	DATE   NULL,
	"C_CHANGE_DATE"  	DATE   NULL,
	"C_STATUS_CD"    	CHAR(1)    NULL ,
     CONSTRAINT ONT_DB_LOOKUP_PK PRIMARY KEY(C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID)
	) ;
	
--------------------------------------------------------
--  DDL for Table WORK_DB_LOOKUP
--------------------------------------------------------
	CREATE TABLE WORK_DB_LOOKUP ( 
	"C_DOMAIN_ID"   	VARCHAR2(255)   NOT NULL,
	"C_PROJECT_PATH" 	VARCHAR2(255)   NOT NULL, 
	"C_OWNER_ID"     	VARCHAR2(255)   NOT NULL, 
	"C_DB_FULLSCHEMA"   VARCHAR2(255)   NOT NULL, 
	"C_DB_DATASOURCE"	VARCHAR2(255)   NOT NULL, 
	"C_DB_SERVERTYPE"	VARCHAR2(255)   NOT NULL, 
	"C_DB_NICENAME"  	VARCHAR2(255)   NULL,
	"C_DB_TOOLTIP"   	VARCHAR2(255)   NULL, 
	"C_COMMENT"      	CLOB   NULL,
	"C_ENTRY_DATE"   	DATE   NULL,
	"C_CHANGE_DATE"  	DATE   NULL,
	"C_STATUS_CD"    	CHAR(1)    NULL ,
     CONSTRAINT WORK_DB_LOOKUP_PK PRIMARY KEY(C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID) 
	)	;

--------------------------------------------------------
--  DDL for Table CRC_DB_LOOKUP
--------------------------------------------------------
	
 CREATE TABLE CRC_DB_LOOKUP ( 
	"C_DOMAIN_ID"   	VARCHAR2(255)	NOT NULL,
	"C_PROJECT_PATH" 	VARCHAR2(255)	NOT NULL, 
	"C_OWNER_ID"     	VARCHAR2(255)	NOT NULL, 
	"C_DB_FULLSCHEMA"   VARCHAR2(255)	NOT NULL, 
	"C_DB_DATASOURCE"	VARCHAR2(255)	NOT NULL, 
	"C_DB_SERVERTYPE"	VARCHAR2(255)	NOT NULL, 
	"C_DB_NICENAME"  	VARCHAR2(255)	NULL,
	"C_DB_TOOLTIP"   	VARCHAR2(255)	NULL, 
	"C_COMMENT"      	CLOB	NULL,
	"C_ENTRY_DATE"   	DATE	NULL,
	"C_CHANGE_DATE"  	DATE	NULL,
	"C_STATUS_CD"    	CHAR(1) NULL,
     CONSTRAINT CRC_DB_LOOKUP_PK PRIMARY KEY(C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID)
	) ;
	
--------------------------------------------------------
--  DDL for Table IM_DB_LOOKUP
--------------------------------------------------------
	
 CREATE TABLE IM_DB_LOOKUP ( 
	"C_DOMAIN_ID"   	VARCHAR2(255)	NOT NULL,
	"C_PROJECT_PATH" 	VARCHAR2(255)	NOT NULL, 
	"C_OWNER_ID"     	VARCHAR2(255)	NOT NULL, 
	"C_DB_FULLSCHEMA"   VARCHAR2(255)	NOT NULL, 
	"C_DB_DATASOURCE"	VARCHAR2(255)	NOT NULL, 
	"C_DB_SERVERTYPE"	VARCHAR2(255)	NOT NULL, 
	"C_DB_NICENAME"  	VARCHAR2(255)	NULL,
	"C_DB_TOOLTIP"   	VARCHAR2(255)	NULL, 
	"C_COMMENT"      	CLOB	NULL,
	"C_ENTRY_DATE"   	DATE	NULL,
	"C_CHANGE_DATE"  	DATE	NULL,
	"C_STATUS_CD"    	CHAR(1) NULL,
     CONSTRAINT IM_DB_LOOKUP_PK PRIMARY KEY(C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID)
	) ;

create table CRC_ANALYSIS_JOB (
	job_id varchar2(10) ,
	queue_name varchar2(50),
	status_type_id int, 
	domain_id varchar(255), 
	project_id varchar(500), 
	user_id varchar(255), 
	request_xml clob,
	create_date date, 
	update_date date,
	CONSTRAINT ANALSIS_JOB_PK PRIMARY KEY(JOB_ID) 
   
) ;

CREATE INDEX CRC_IDX_AJ_QNSTID ON CRC_ANALYSIS_JOB(queue_name,status_type_id);

CREATE TABLE HIVE_CELL_PARAMS  ( 
	ID           	NUMBER NOT NULL,
	DATATYPE_CD  	VARCHAR2(50) NULL,
	CELL_ID      	VARCHAR2(50) NOT NULL,
	PARAM_NAME_CD	VARCHAR2(2000) NOT NULL,
	VALUE        	CLOB NULL,
	CHANGE_DATE  	DATE NULL,
	ENTRY_DATE   	DATE NULL,
	CHANGEBY_CHAR	VARCHAR2(50) NULL,
	STATUS_CD    	VARCHAR2(50) NULL,
	CONSTRAINT HIVE_CE__PK PRIMARY KEY(ID)
) ;

 INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(33, 'T', 'CRC', 'queryprocessor.jndi.queryinfolocal', 'ejb.querytool.QueryInfoLocal', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(31, 'T', 'CRC', 'queryprocessor.jndi.querymanagerlocal', 'ejb.querytool.QueryManagerLocal', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(37, 'T', 'CRC', 'queryprocessor.jndi.querymanagerremote', 'ejb.querytool.QueryManager', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(61, 'T', 'ONT', 'applicationName', 'Ontology Cell', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(63, 'T', 'CRC', 'applicationName', 'CRC Cell', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(62, 'T', 'ONT', 'applicationVersion', '1.7', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(64, 'T', 'CRC', 'applicationVersion', '1.7', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(16, 'T', 'CRC', 'edu.harvard.i2b2.crc.analysis.queue.large.jobcheck.timemills', '60000', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(14, 'T', 'CRC', 'edu.harvard.i2b2.crc.analysis.queue.large.maxjobcount', '1', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(13, 'T', 'CRC', 'edu.harvard.i2b2.crc.analysis.queue.large.timeoutmills', '43200000', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(15, 'T', 'CRC', 'edu.harvard.i2b2.crc.analysis.queue.medium.jobcheck.timemills', '60000', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(12, 'T', 'CRC', 'edu.harvard.i2b2.crc.analysis.queue.medium.maxjobcount', '4', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(11, 'T', 'CRC', 'edu.harvard.i2b2.crc.analysis.queue.medium.timeoutmills', '3000', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(2, 'T', 'CRC', 'edu.harvard.i2b2.crc.delegate.ontology.operation.getchildren', '/getChildren', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(3, 'T', 'CRC', 'edu.harvard.i2b2.crc.delegate.ontology.operation.getmodifierinfo', '/getModifierInfo', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(1, 'T', 'CRC', 'edu.harvard.i2b2.crc.delegate.ontology.operation.getterminfo', '/getTermInfo', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(67, 'U', 'CRC', 'edu.harvard.i2b2.crc.delegate.ontology.url', '/services/OntologyService', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(28, 'T', 'CRC', 'edu.harvard.i2b2.crc.i2b2SocketServer', '7070', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(19, 'T', 'CRC', 'edu.harvard.i2b2.crc.jms.large.timeoutsec', '43200', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(18, 'T', 'CRC', 'edu.harvard.i2b2.crc.jms.medium.timeoutsec', '14400', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(17, 'T', 'CRC', 'edu.harvard.i2b2.crc.jms.small.timeoutsec', '180', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(22, 'T', 'CRC', 'edu.harvard.i2b2.crc.lockout.setfinderquery.count', '7', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(23, 'T', 'CRC', 'edu.harvard.i2b2.crc.lockout.setfinderquery.day', '30', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(24, 'T', 'CRC', 'edu.harvard.i2b2.crc.lockout.setfinderquery.zero.count', '-1', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(7, 'T', 'CRC', 'edu.harvard.i2b2.crc.pdo.paging.inputlist.minpercent', '20', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(8, 'T', 'CRC', 'edu.harvard.i2b2.crc.pdo.paging.inputlist.minsize', '1', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(6, 'T', 'CRC', 'edu.harvard.i2b2.crc.pdo.paging.iteration', '100', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(9, 'T', 'CRC', 'edu.harvard.i2b2.crc.pdo.paging.method', 'SUBDIVIDE_INPUT_METHOD ', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(5, 'T', 'CRC', 'edu.harvard.i2b2.crc.pdo.paging.observation.size', '7500', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(10, 'T', 'CRC', 'edu.harvard.i2b2.crc.pdo.request.timeoutmills', '600000', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(21, 'T', 'CRC', 'edu.harvard.i2b2.crc.pm.serviceaccount.password', 'demouser', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(20, 'T', 'CRC', 'edu.harvard.i2b2.crc.pm.serviceaccount.user', 'AGG_SERVICE_ACCOUNT', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(66, 'T', 'CRC', 'edu.harvard.i2b2.crc.setfinder.querygenerator.version', '1.7', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(26, 'T', 'CRC', 'edu.harvard.i2b2.crc.setfinderquery.obfuscation.breakdowncount.sigma', '1.6', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(25, 'T', 'CRC', 'edu.harvard.i2b2.crc.setfinderquery.obfuscation.count.sigma', '1.323', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(27, 'T', 'CRC', 'edu.harvard.i2b2.crc.setfinderquery.obfuscation.minimum.value', '3', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(29, 'T', 'CRC', 'edu.harvard.i2b2.crc.setfinderquery.skiptemptable.maxconcept', '40', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(54, 'U', 'ONT', 'edu.harvard.i2b2.ontology.ws.crc.url', '/services/QueryToolService', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(59, 'T', 'ONT', 'edu.harvard.i2b2.ontology.ws.fr.attachmentname', 'cid', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(58, 'T', 'ONT', 'edu.harvard.i2b2.ontology.ws.fr.filethreshold', '4000', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(60, 'T', 'ONT', 'edu.harvard.i2b2.ontology.ws.fr.operation', 'urn:recvfileRequest', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(56, 'T', 'ONT', 'edu.harvard.i2b2.ontology.ws.fr.tempspace', '/tmp', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(57, 'T', 'ONT', 'edu.harvard.i2b2.ontology.ws.fr.timeout', '10000', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(55, 'U', 'ONT', 'edu.harvard.i2b2.ontology.ws.fr.url', '/services/FRService/', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(42, 'T', 'CRC', 'I2B2_MESSAGE_ERROR_AUTHENTICATION_FAILURE', 'Authentication failure.', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(43, 'T', 'CRC', 'I2B2_MESSAGE_ERROR_INVALID_MESSAGE', 'Invalid message body', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(48, 'T', 'CRC', 'I2B2_MESSAGE_STATUS_COMPLETED', 'COMPLETED', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(46, 'T', 'CRC', 'I2B2_MESSAGE_STATUS_ERROR', 'ERROR', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(47, 'T', 'CRC', 'I2B2_MESSAGE_STATUS_FINISHED', 'FINISHED', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(49, 'T', 'CRC', 'I2B2_MESSAGE_STATUS_INCOMPLE', 'INCOMPLETE', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(45, 'T', 'CRC', 'I2B2_MESSAGE_STATUS_PROCESSING', 'PROCESSING', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(44, 'T', 'CRC', 'I2B2_MESSAGE_STATUS_QUEUED', 'QUEUED', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(65, 'T', 'ONT', 'ontology.terminal.delimiter', 'true', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(53, 'U', 'ONT', 'ontology.ws.pm.url', '/services/PMService/getServices', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(36, 'T', 'CRC', 'queryprocessor.jndi.pdoquerylocal', 'ejb.querytool.PdoQueryLocal', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(30, 'T', 'CRC', 'queryprocessor.jndi.queryexecutormdblocal', 'ejb.querytool.QueryExecutorMDBLocal', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(38, 'T', 'CRC', 'queryprocessor.jndi.queryexecutormdbremote', 'ejb.querytool.QueryExecutorMDB', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(32, 'T', 'CRC', 'queryprocessor.jndi.querymasterlocal', 'ejb.querytool.QueryMasterLocal', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(35, 'T', 'CRC', 'queryprocessor.jndi.queryresultlocal', 'ejb.querytool.QueryResultLocal', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(34, 'T', 'CRC', 'queryprocessor.jndi.queryrunlocal', 'ejb.querytool.QueryRunLocal', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(39, 'T', 'CRC', 'queryprocessor.jndi.queue.connectionfactory', 'ConnectionFactory', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(41, 'T', 'CRC', 'queryprocessor.jndi.queue.executor_queue', 'queue/jms.querytool.QueryExecutor', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(40, 'T', 'CRC', 'queryprocessor.jndi.queue.response_queue', 'queue/jms.querytool.QueryResponse', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(4, 'T', 'CRC', 'queryprocessor.multifacttable', 'false', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(50, 'U', 'CRC', 'queryprocessor.ws.ontology.url', '/services/OntologyService/getTermInfo', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(51, 'U', 'CRC', 'queryprocessor.ws.pm.url', '/services/PMService/getServices', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(52, 'U', 'WORK', 'workplace.ws.pm.url', '/services/PMService/getServices', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(68, 'U', 'IM', 'im.ws.pm.url', '/services/PMService/getServices', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(69, 'T', 'IM', 'im.checkPatientInProject', 'true', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(70, 'T', 'IM', 'im.empi.service', 'none', NULL, NULL, NULL, 'A');
INSERT INTO HIVE_CELL_PARAMS(ID, DATATYPE_CD, CELL_ID, PARAM_NAME_CD, VALUE, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES(71, 'U', 'ONT', 'edu.harvard.i2b2.ontology.stopword', 'a,able,about,across,after,all,almost,also,am,among,an,and,any,are,as,at,be,because,been,but,by,can,cannot,could,dear,did,do,does,either,else,ever,every,for,from,get,got,had,has,have,he,her,hers,him,his,how,however,i,if,in,into,is,it,its,just,least,let,like,likely,may,me,might,most,must,my,neither,no,nor,not,of,off,often,on,only,or,other,our,own,rather,said,say,says,she,should,since,so,some,than,that,the,their,them,then,there,these,they,this,tis,to,too,twas,us,wants,was,we,were,what,when,where,which,while,who,whom,why,will,with,would,yet,you,your', NULL, NULL, NULL, 'A');
  
  
  
