DROP PROCEDURE CREATE_TEMP_CONCEPT_TABLE
;
DROP PROCEDURE CREATE_TEMP_PATIENT_TABLE
;
DROP PROCEDURE CREATE_TEMP_PID_TABLE
;
DROP PROCEDURE CREATE_TEMP_EID_TABLE
;
DROP PROCEDURE CREATE_TEMP_MODIFIER_TABLE
;
DROP PROCEDURE CREATE_TEMP_PROVIDER_TABLE
;
DROP PROCEDURE CREATE_TEMP_TABLE
;
DROP PROCEDURE CREATE_TEMP_VISIT_TABLE
;
DROP PROCEDURE INSERT_CONCEPT_FROMTEMP
;
DROP PROCEDURE INSERT_ENCOUNTERVISIT_FROMTEMP
;
DROP PROCEDURE INSERT_PATIENT_MAP_FROMTEMP
;
DROP PROCEDURE INSERT_PID_MAP_FROMTEMP
;
DROP PROCEDURE INSERT_EID_MAP_FROMTEMP
;
DROP PROCEDURE INSERT_PROVIDER_FROMTEMP
;
DROP PROCEDURE INSERT_MODIFIER_FROMTEMP
;
DROP PROCEDURE REMOVE_TEMP_TABLE
;
DROP PROCEDURE UPDATE_OBSERVATION_FACT
;
DROP PROCEDURE SYNC_CLEAR_CONCEPT_TABLE
;
DROP PROCEDURE SYNC_CLEAR_PROVIDER_TABLE
;
DROP PROCEDURE SYNC_CLEAR_MODIFIER_TABLE
;
DROP PROCEDURE UPDATE_QUERYINSTANCE_MESSAGE
;




