--------------------------------------------------------
--  DDL for Table PHI
--------------------------------------------------------

CREATE TABLE PHI (
	"C_HLEVEL"				NUMBER(22,0)	NOT NULL, 
	"C_FULLNAME"			VARCHAR2(700)	NOT NULL, 
	"C_NAME"				VARCHAR2(2000)	NOT NULL, 
	"C_SYNONYM_CD"			CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES"	CHAR(3)	NOT NULL, 
	"C_TOTALNUM"			NUMBER(22,0)	NULL, 
	"C_BASECODE"			VARCHAR2(50)	NULL, 
	"C_METADATAXML"			CLOB	NULL, 
	"C_FACTTABLECOLUMN"		VARCHAR2(50)	NOT NULL, 
	"C_TABLENAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNNAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNDATATYPE"		VARCHAR2(50)	NOT NULL, 
	"C_OPERATOR"			VARCHAR2(10)	NOT NULL, 
	"C_DIMCODE"				VARCHAR2(700)	NOT NULL, 
	"C_COMMENT"				CLOB	NULL, 
	"C_TOOLTIP"				VARCHAR2(900)	NULL, 
	"M_APPLIED_PATH"		VARCHAR2(700)	NOT NULL, 
	"UPDATE_DATE"			DATE	NOT NULL, 
	"DOWNLOAD_DATE"			DATE	NULL, 
	"IMPORT_DATE"			DATE	NULL, 
	"SOURCESYSTEM_CD"		VARCHAR2(50)	NULL, 
	"VALUETYPE_CD"			VARCHAR2(50)	NULL,
	"M_EXCLUSION_CD"			VARCHAR2(25) NULL,
	"C_PATH"				VARCHAR2(700)   NULL,
	"C_SYMBOL"				VARCHAR2(50)	NULL
)
;
CREATE INDEX META_FULLNAME_PHI_IDX ON PHI(C_FULLNAME)
;
CREATE INDEX META_APPLIED_PATH_PHI_IDX ON PHI(M_APPLIED_PATH)
;
CREATE INDEX META_EXCLUSION_PHI_IDX ON PHI(M_EXCLUSION_CD)
;
CREATE INDEX META_HLEVEL_PHI_IDX ON PHI(C_HLEVEL)
;
CREATE INDEX META_SYNONYM_PHI_IDX ON PHI(C_SYNONYM_CD)
;
INSERT INTO TABLE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_DIMTABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, C_ENTRY_DATE, C_CHANGE_DATE, C_STATUS_CD, VALUETYPE_CD, C_ONTOLOGY_PROTECTION)
  VALUES('PHI', 'PHI', 'Y', 0, '\PHI\', 'Protected Health Information', 'N', 'CA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\PHI\', NULL, 'PHI', NULL, NULL, NULL, NULL, 'DATA_PROT');
INSERT INTO PHI(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_EXCLUSION_CD, C_PATH, C_SYMBOL)
  VALUES(1, '\PHI\First Name\', 'First Name', 'N', 'LA ', NULL, 'PHI:FNAME', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-10-19T13:32:16.198-04:00</CreationDateTime><TestID>PHI:FNAME</TestID><TestName>First Name</TestName><DataType>String</DataType><MaxStringLength>50</MaxStringLength><Flagstouse>A</Flagstouse><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\PHI\First Name\', NULL, 'First Name', '@', TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), 'PHI', NULL, NULL, NULL, NULL);
INSERT INTO PHI(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_EXCLUSION_CD, C_PATH, C_SYMBOL)
  VALUES(0, '\PHI\', 'PHI', 'N', 'FA ', NULL, NULL, NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\PHI\', NULL, 'PHI', '@', TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), 'PHI', NULL, NULL, NULL, NULL);
INSERT INTO PHI(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_EXCLUSION_CD, C_PATH, C_SYMBOL)
  VALUES(1, '\PHI\Last Name\', 'Last Name', 'N', 'LA ', NULL, 'PHI:LNAME', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-10-19T13:32:16.198-04:00</CreationDateTime><TestID>PHI:LNAME</TestID><TestName>Last Name</TestName><DataType>String</DataType><MaxStringLength>50</MaxStringLength><Flagstouse>A</Flagstouse><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\PHI\Last Name\', NULL, 'Last Name', '@', TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), 'PHI', NULL, NULL, NULL, NULL);
INSERT INTO PHI(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, M_APPLIED_PATH, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_EXCLUSION_CD, C_PATH, C_SYMBOL)
  VALUES(1, '\PHI\MRN\', 'MRN', 'N', 'LA ', NULL, 'PHI:MRN', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-10-19T13:32:16.198-04:00</CreationDateTime><TestID>PHI:MRN</TestID><TestName>Medical Record Number</TestName><DataType>String</DataType><MaxStringLength>50</MaxStringLength><Flagstouse>A</Flagstouse><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\PHI\MRN\', NULL, 'MRN', '@', TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-10-18 08:16:08','YYYY-MM-DD HH24:MI:SS'), 'PHI', NULL, NULL, NULL, NULL);
  