-----------------------------------------------------------------------------------------------------------------
-- Totalnum patient counting script refactored - speed improvement, support for ACT-OMOP. 
--   This version by Darren Henderson (DARREN.HENDERSON@UKY.EDU) and Jeff Klann, PhD.
--   Based on code by Griffin Weber, Jeff Klann, Mike Mendis, Lori Phillips, Jeff Green, and Darren Henderson.

--   NOTE: ONTOLOGY TABLE NAMES CORRESPONDING TO PATIENT/VISIT DIMENSION ARE HARDCODED. */   
-- Last updated: July 2023
-----------------------------------------------------------------------------------------------------------------
/* SET TARGET DATABASE */
--USE I2B2ACT
--GO


/****************************************************************/
/* BASED ON ACT V41 ONTOLOGY                                     */
/* PATHS FROM TABLE_ACCESS FOR MANAGING MULTITABLE ONTOLOGY     */
/* SITE MAY CUSTOMIZE THIS STEP TO FULLY CAPTURE THEIR ONTOLOGY */
/****************************************************************/

IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'FastTotalnumCount')
                    AND type IN ( N'P', N'PC' ) ) 
DROP PROCEDURE FastTotalnumCount;
GO

CREATE PROCEDURE [dbo].[FastTotalnumCount]  

AS BEGIN
declare @sqlstr nvarchar(4000)
declare @startime datetime

set @startime = getdate(); 

/* CLEAR OUT TEMP OBJECTS FROM PREVIOUS RUN */
--DROP TABLE IF EXISTS #ONTOLOGY;
--DROP TABLE IF EXISTS #CONCEPT_CLOSURE;
--DROP TABLE IF EXISTS #PV_FACT_PAIRS;

/********************************************/


/* BUILD PAT/VIS DIM FEATURES AS FACT TUPLES */
/* DWHenderson: A major overhaul of the age calculations was proprosed in June 2024 to bring this codebase closer to the existing ontology methodology for caculating age at visit */
/* Methods were evaluated and iterative approached were avoided at all costs. The new approach is neigh unreadable, but is merely a straight copy of the dimcodes from the ACT v41 ontology */
/* for each age bucket. This produces totalnum counts that more accurately align with counts that would be produced by end-user queries at each site. */
/* In future versions we can deprecate and remove the old blocks of code. */

CREATE TABLE #PV_FACT_PAIRS (PATIENT_NUM INT, CONCEPT_CD VARCHAR(50), PRIMARY KEY (PATIENT_NUM, CONCEPT_CD));

;WITH PATIENT_VISIT_PRELIM AS (
SELECT P.PATIENT_NUM
/* AGEV CHANGE DWH
  --, FLOOR(DATEDIFF(DD,P.BIRTH_DATE,GETDATE())/365.25) AS AGE_TODAY_NUM
  --, CONCAT('DEM|AGE:'
  --    , CASE WHEN FLOOR(DATEDIFF(DD,P.BIRTH_DATE,GETDATE())/365.25)>=3 /* AFTER 3YO AGE IS INT */
  --           THEN CAST(FLOOR(DATEDIFF(DD,P.BIRTH_DATE,GETDATE())/365.25) AS VARCHAR(5)) 
  --           /* UNDER 3 AGE IS YR + NUM MON = DATEDIFF MO/12 || DATEDIFF MO%12 */
  --           ELSE CONCAT(CAST(DATEDIFF(MM,P.BIRTH_DATE,GETDATE())/12 AS VARCHAR(5)),'.',CAST(DATEDIFF(MM,P.BIRTH_DATE,GETDATE())%12 AS VARCHAR(5)))
  --           END) AS AGE_TODAY_CHAR
  --, FLOOR(DATEDIFF(DD,P.BIRTH_DATE,V.START_DATE)/365.25) AS AGE_VISIT_NUM
  --, CONCAT('VIS|AGE:'
  --    , CASE WHEN FLOOR(DATEDIFF(DD,P.BIRTH_DATE,V.START_DATE)/365.25) >=3 /* AFTER 3YO AGE IS INT */
  --           THEN CAST(FLOOR(DATEDIFF(DD,P.BIRTH_DATE,V.START_DATE)/365.25) AS VARCHAR(5))
  --          /* UNDER 3 AGE IS YR + NUM MON = DATEDIFF MO/12 || DATEDIFF MO%12 */
  --           ELSE CONCAT(CAST(DATEDIFF(MM,P.BIRTH_DATE,V.START_DATE)/12 AS VARCHAR(5)),'.',CAST(DATEDIFF(MM,P.BIRTH_DATE,V.START_DATE)%12 AS VARCHAR(5)))
  --           END) AS AGE_VISIT_CHAR
*/
  , CONCAT('visit_dimension|length_of_stay:',CAST(DATEDIFF(DD,V.START_DATE,V.END_DATE) AS VARCHAR(5))) AS LENGTH_OF_STAY
  , CASE WHEN DATEDIFF(DD,V.START_DATE,V.END_DATE)>=10 THEN 'visit_dimension|length_of_stay:>10' END AS LENGTH_OF_STAY_GTE10
  , CONCAT('visit_dimension|inout_cd:',V.INOUT_CD) AS inout_cd
  , P.RACE_CD, P.SEX_CD /* THESE CONCEPTS CAN BE COMMENTED OUT AT SITES THAT STORE RACE AND SEX IN OBSERVATION_FACT ALREADY - IF PULLED HERE CONFIRM THAT THE SEX_CD AND RACE_CD ARE STORED IN PATIENT_DIMENSION WITH APPROPRIATE CONCEPT_CD STYLE PREFIXES THAT MATCH ACT_DEM_V41 C_BASECODE OR AFFIX THEM WITH CONCATENATION EXAMPLE: CONCAT('DEM|SEX:',SEX_CD) */
FROM DBO.PATIENT_DIMENSION P
  JOIN DBO.VISIT_DIMENSION V
    ON P.PATIENT_NUM = V.PATIENT_NUM
)
INSERT INTO #PV_FACT_PAIRS(PATIENT_NUM, CONCEPT_CD)
SELECT DISTINCT PATIENT_NUM, VAL AS CONCEPT_CD
FROM (
SELECT PATIENT_NUM
/* AGEV CHANGE DWH
  --, CAST(AGE_TODAY_CHAR AS VARCHAR(50)) AS AGE_TODAY
  --, CAST(AGE_VISIT_CHAR AS VARCHAR(50)) AS AGE_VISIT
  --, CAST(CASE WHEN AGE_TODAY_NUM < 18 THEN  'DEM|AGE:<18'  ELSE NULL END AS VARCHAR(50)) AS AGE_TODAY_LT18
  --, CAST(CASE WHEN AGE_TODAY_NUM >= 18 THEN 'DEM|AGE:>=18' ELSE NULL END AS VARCHAR(50)) AS AGE_TODAY_GTE18
  --, CAST(CASE WHEN AGE_TODAY_NUM >= 65 THEN 'DEM|AGE:>=65' ELSE NULL END AS VARCHAR(50)) AS AGE_TODAY_GTE65
  --, CAST(CASE WHEN AGE_TODAY_NUM >= 85 THEN 'DEM|AGE:>=85' ELSE NULL END AS VARCHAR(50)) AS AGE_TODAY_GTE85
  --, CAST(CASE WHEN AGE_TODAY_NUM >= 90 THEN 'DEM|AGE:>=90' ELSE NULL END AS VARCHAR(50)) AS AGE_TODAY_GTE90
  --, CAST(CASE WHEN AGE_VISIT_NUM >= 65 THEN 'VIS|AGE:>=65' ELSE NULL END AS VARCHAR(50)) AS AGE_VISIT_GTE65
  --, CAST(CASE WHEN AGE_VISIT_NUM >= 85 THEN 'VIS|AGE:>=85' ELSE NULL END AS VARCHAR(50)) AS AGE_VISIT_GTE85
  --, CAST(CASE WHEN AGE_VISIT_NUM >= 90 THEN 'VIS|AGE:>=90' ELSE NULL END AS VARCHAR(50)) AS AGE_VISIT_GTE90
*/
  , CAST(LENGTH_OF_STAY       AS VARCHAR(50)) AS LENGTH_OF_STAY
  , CAST(LENGTH_OF_STAY_GTE10 AS VARCHAR(50)) AS LENGTH_OF_STAY_GTE10
  , CAST(INOUT_CD             AS VARCHAR(50)) AS INOUT_CD
  , CAST(RACE_CD             AS VARCHAR(50)) AS RACE_CD
  , CAST(SEX_CD             AS VARCHAR(50)) AS SEX_CD
FROM PATIENT_VISIT_PRELIM
)O
UNPIVOT
(VAL FOR FACT IN (/*[AGE_TODAY],[AGE_VISIT], [AGE_TODAY_LT18]
  , AGE_TODAY_GTE18, AGE_TODAY_GTE65, AGE_TODAY_GTE85, AGE_TODAY_GTE90
  , AGE_VISIT_GTE65, AGE_VISIT_GTE85, AGE_VISIT_GTE90*/
  LENGTH_OF_STAY, LENGTH_OF_STAY_GTE10, INOUT_CD, RACE_CD, SEX_CD))P
;

/* CREATE NEW DIMCODE BASED PATIENT AGE (TODAY) AND PATIENT AGE AT VISIT CONCEPT STYLE FACT PAIRS */
;WITH CTE_AGE_TODAY_PATIENT_FACTS AS (
SELECT PATIENT_NUM,'\ACT\Demographics\Age\< 18 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE > dateadd(YY, -18, GETDATE()) 
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\>= 90 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE <= dateadd(YY, -90, GETDATE()) 
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\>= 18 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE <= dateadd(YY, -18, GETDATE()) 
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\>= 85 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE <= dateadd(YY, -85, GETDATE()) 
UNION  SELECT PATIENT_NUM,'DEM|AGE:1' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -2, dateadd(dd, +1,getdate())) AND dateadd(YY, -1, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -3, dateadd(dd, +1,getdate())) AND dateadd(YY, -2, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:3' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, - 4, dateadd(dd, +1,getdate())) AND dateadd(YY, -3, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:4' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, - 5, dateadd(dd, +1,getdate())) AND dateadd(YY, -4, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:5' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, - 6, dateadd(dd, +1,getdate())) AND dateadd(YY, -5, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:6' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, - 7, dateadd(dd, +1,getdate())) AND dateadd(YY, -6, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:7' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, - 8, dateadd(dd, +1,getdate())) AND dateadd(YY, -7, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:8' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, - 9, dateadd(dd, +1,getdate())) AND dateadd(YY, -8, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:9' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -10, dateadd(dd, +1,getdate())) AND dateadd(YY, -9, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:10' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -11, dateadd(dd, +1,getdate())) AND dateadd(YY, -10, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:11' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -12, dateadd(dd, +1,getdate())) AND dateadd(YY, -11, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:12' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -13, dateadd(dd, +1,getdate())) AND dateadd(YY, -12, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:13' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -14, dateadd(dd, +1,getdate())) AND dateadd(YY, -13, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:14' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -15, dateadd(dd, +1,getdate())) AND dateadd(YY, -14, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:15' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -16, dateadd(dd, +1,getdate())) AND dateadd(YY, -15, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:16' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -17, dateadd(dd, +1,getdate())) AND dateadd(YY, -16, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:17' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -18, dateadd(dd, +1,getdate())) AND dateadd(YY, -17, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:18' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -19, dateadd(dd, +1,getdate())) AND dateadd(YY, -18, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:19' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -20, dateadd(dd, +1,getdate())) AND dateadd(YY, -19, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:20' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -21, dateadd(dd, +1,getdate())) AND dateadd(YY, -20, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:21' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -22, dateadd(dd, +1,getdate())) AND dateadd(YY, -21, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:22' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -23, dateadd(dd, +1,getdate())) AND dateadd(YY, -22, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:23' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -24, dateadd(dd, +1,getdate())) AND dateadd(YY, -23, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:24' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -25, dateadd(dd, +1,getdate())) AND dateadd(YY, -24, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:25' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -26, dateadd(dd, +1,getdate())) AND dateadd(YY, -25, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:26' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -27, dateadd(dd, +1,getdate())) AND dateadd(YY, -26, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:27' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -28, dateadd(dd, +1,getdate())) AND dateadd(YY, -27, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:28' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -29, dateadd(dd, +1,getdate())) AND dateadd(YY, -28, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:29' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -30, dateadd(dd, +1,getdate())) AND dateadd(YY, -29, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:30' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -31, dateadd(dd, +1,getdate())) AND dateadd(YY, -30, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:31' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -32, dateadd(dd, +1,getdate())) AND dateadd(YY, -31, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:32' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -33, dateadd(dd, +1,getdate())) AND dateadd(YY, -32, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:33' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -34, dateadd(dd, +1,getdate())) AND dateadd(YY, -33, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:34' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -35, dateadd(dd, +1,getdate())) AND dateadd(YY, -34, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:35' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -36, dateadd(dd, +1,getdate())) AND dateadd(YY, -35, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:36' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -37, dateadd(dd, +1,getdate())) AND dateadd(YY, -36, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:37' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -38, dateadd(dd, +1,getdate())) AND dateadd(YY, -37, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:38' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -39, dateadd(dd, +1,getdate())) AND dateadd(YY, -38, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:39' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -40, dateadd(dd, +1,getdate())) AND dateadd(YY, -39, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:40' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -41, dateadd(dd, +1,getdate())) AND dateadd(YY, -40, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:41' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -42, dateadd(dd, +1,getdate())) AND dateadd(YY, -41, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:42' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -43, dateadd(dd, +1,getdate())) AND dateadd(YY, -42, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:43' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -44, dateadd(dd, +1,getdate())) AND dateadd(YY, -43, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:44' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -45, dateadd(dd, +1,getdate())) AND dateadd(YY, -44, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:45' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -46, dateadd(dd, +1,getdate())) AND dateadd(YY, -45, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:46' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -47, dateadd(dd, +1,getdate())) AND dateadd(YY, -46, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:47' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -48, dateadd(dd, +1,getdate())) AND dateadd(YY, -47, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:48' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -49, dateadd(dd, +1,getdate())) AND dateadd(YY, -48, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:49' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -50, dateadd(dd, +1,getdate())) AND dateadd(YY, -49, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:50' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -51, dateadd(dd, +1,getdate())) AND dateadd(YY, -50, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:51' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -52, dateadd(dd, +1,getdate())) AND dateadd(YY, -51, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:52' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -53, dateadd(dd, +1,getdate())) AND dateadd(YY, -52, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:53' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -54, dateadd(dd, +1,getdate())) AND dateadd(YY, -53, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:54' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -55, dateadd(dd, +1,getdate())) AND dateadd(YY, -54, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:55' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -56, dateadd(dd, +1,getdate())) AND dateadd(YY, -55, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:56' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -57, dateadd(dd, +1,getdate())) AND dateadd(YY, -56, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:57' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -58, dateadd(dd, +1,getdate())) AND dateadd(YY, -57, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:58' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -59, dateadd(dd, +1,getdate())) AND dateadd(YY, -58, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:59' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -60, dateadd(dd, +1,getdate())) AND dateadd(YY, -59, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:60' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -61, dateadd(dd, +1,getdate())) AND dateadd(YY, -60, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:61' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -62, dateadd(dd, +1,getdate())) AND dateadd(YY, -61, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:62' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -63, dateadd(dd, +1,getdate())) AND dateadd(YY, -62, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:63' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -64, dateadd(dd, +1,getdate())) AND dateadd(YY, -63, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:64' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -65, dateadd(dd, +1,getdate())) AND dateadd(YY, -64, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:65' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -66, dateadd(dd, +1,getdate())) AND dateadd(YY, -65, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:66' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -67, dateadd(dd, +1,getdate())) AND dateadd(YY, -66, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:67' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -68, dateadd(dd, +1,getdate())) AND dateadd(YY, -67, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:68' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -69, dateadd(dd, +1,getdate())) AND dateadd(YY, -68, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:69' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -70, dateadd(dd, +1,getdate())) AND dateadd(YY, -69, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:70' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -71, dateadd(dd, +1,getdate())) AND dateadd(YY, -70, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:71' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -72, dateadd(dd, +1,getdate())) AND dateadd(YY, -71, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:72' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -73, dateadd(dd, +1,getdate())) AND dateadd(YY, -72, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:73' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -74, dateadd(dd, +1,getdate())) AND dateadd(YY, -73, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:74' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -75, dateadd(dd, +1,getdate())) AND dateadd(YY, -74, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:75' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -76, dateadd(dd, +1,getdate())) AND dateadd(YY, -75, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:76' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -77, dateadd(dd, +1,getdate())) AND dateadd(YY, -76, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:77' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -78, dateadd(dd, +1,getdate())) AND dateadd(YY, -77, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:78' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -79, dateadd(dd, +1,getdate())) AND dateadd(YY, -78, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:79' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -80, dateadd(dd, +1,getdate())) AND dateadd(YY, -79, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:80' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -81, dateadd(dd, +1,getdate())) AND dateadd(YY, -80, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:81' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -82, dateadd(dd, +1,getdate())) AND dateadd(YY, -81, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:82' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -83, dateadd(dd, +1,getdate())) AND dateadd(YY, -82, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:83' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -84, dateadd(dd, +1,getdate())) AND dateadd(YY, -83, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:84' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -85, dateadd(dd, +1,getdate())) AND dateadd(YY, -84, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:85' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -86, dateadd(dd, +1,getdate())) AND dateadd(YY, -85, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:86' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -87, dateadd(dd, +1,getdate())) AND dateadd(YY, -86, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:87' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -88, dateadd(dd, +1,getdate())) AND dateadd(YY, -87, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:88' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -89, dateadd(dd, +1,getdate())) AND dateadd(YY, -88, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:89' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -90, dateadd(dd, +1,getdate())) AND dateadd(YY, -89, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\0-9 years old\0 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -1, dateadd(dd, +1,getdate())) AND dateadd(YY, -0, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.1' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -2, dateadd(dd, +1,getdate())) AND dateadd(MM, -1, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.10' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -11, dateadd(dd, +1,getdate())) AND dateadd(MM, -10, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.11' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -12, dateadd(dd, +1,getdate())) AND dateadd(MM, -11, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.12' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -13, dateadd(dd, +1,getdate())) AND dateadd(MM, -12, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.1' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -14, dateadd(dd, +1,getdate())) AND dateadd(MM, -13, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.2' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -15, dateadd(dd, +1,getdate())) AND dateadd(MM, -14, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.3' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -16, dateadd(dd, +1,getdate())) AND dateadd(MM, -15, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.4' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -17, dateadd(dd, +1,getdate())) AND dateadd(MM, -16, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.5' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -18, dateadd(dd, +1,getdate())) AND dateadd(MM, -17, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.6' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -19, dateadd(dd, +1,getdate())) AND dateadd(MM, -18, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.7' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -20, dateadd(dd, +1,getdate())) AND dateadd(MM, -19, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.2' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -3, dateadd(dd, +1,getdate())) AND dateadd(MM, -2, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.8' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -21, dateadd(dd, +1,getdate())) AND dateadd(MM, -20, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.9' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -22, dateadd(dd, +1,getdate())) AND dateadd(MM, -21, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.10' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -23, dateadd(dd, +1,getdate())) AND dateadd(MM, -22, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.11' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -24, dateadd(dd, +1,getdate())) AND dateadd(MM, -23, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:1.12' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -25, dateadd(dd, +1,getdate())) AND dateadd(MM, -24, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.1' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -26, dateadd(dd, +1,getdate())) AND dateadd(MM, -25, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.2' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -27, dateadd(dd, +1,getdate())) AND dateadd(MM, -26, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.3' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -28, dateadd(dd, +1,getdate())) AND dateadd(MM, -27, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.4' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -29, dateadd(dd, +1,getdate())) AND dateadd(MM, -28, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.5' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -30, dateadd(dd, +1,getdate())) AND dateadd(MM, -29, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.3' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -4, dateadd(dd, +1,getdate())) AND dateadd(MM, -3, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.6' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -31, dateadd(dd, +1,getdate())) AND dateadd(MM, -30, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.7' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -32, dateadd(dd, +1,getdate())) AND dateadd(MM, -31, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.8' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -33, dateadd(dd, +1,getdate())) AND dateadd(MM, -32, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.9' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -34, dateadd(dd, +1,getdate())) AND dateadd(MM, -33, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.10' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -35, dateadd(dd, +1,getdate())) AND dateadd(MM, -34, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.11' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -36, dateadd(dd, +1,getdate())) AND dateadd(MM, -35, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:2.12' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -37, dateadd(dd, +1,getdate())) AND dateadd(MM, -36, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.4' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -5, dateadd(dd, +1,getdate())) AND dateadd(MM, -4, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.5' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -6, dateadd(dd, +1,getdate())) AND dateadd(MM, -5, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.6' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -7, dateadd(dd, +1,getdate())) AND dateadd(MM, -6, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.7' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -8, dateadd(dd, +1,getdate())) AND dateadd(MM, -7, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.8' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -9, dateadd(dd, +1,getdate())) AND dateadd(MM, -8, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:0.9' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(MM, -10, dateadd(dd, +1,getdate())) AND dateadd(MM, -9, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\0-9 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -10, dateadd(dd, +1,getdate())) AND dateadd(YY, -0, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\10-17 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -18, dateadd(dd, +1,getdate())) AND dateadd(YY, -10, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\18-34 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -35, dateadd(dd, +1,getdate())) AND dateadd(YY, -18, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\35-44 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -45, dateadd(dd, +1,getdate())) AND dateadd(YY, -35, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\45-54 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -55, dateadd(dd, +1,getdate())) AND dateadd(YY, -45, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\55-64 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -65, dateadd(dd, +1,getdate())) AND dateadd(YY, -55, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\65-74 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -75, dateadd(dd, +1,getdate())) AND dateadd(YY, -65, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\75-84 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -85, dateadd(dd, +1,getdate())) AND dateadd(YY, -74, getdate())
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\85-89 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE BETWEEN dateadd(YY, -90, dateadd(dd, +1,getdate())) AND dateadd(YY, -85, getdate())
UNION  SELECT PATIENT_NUM,'DEM|AGE:-1' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE IS NULL
UNION  SELECT PATIENT_NUM,'\ACT\Demographics\Age\>= 65 years old\' AS CONCEPT_CD FROM DBO.PATIENT_DIMENSION WHERE BIRTH_DATE <= dateadd(YY, -65, GETDATE()) 
)
INSERT INTO #PV_FACT_PAIRS WITH(TABLOCK)(PATIENT_NUM, CONCEPT_CD)
SELECT DISTINCT PATIENT_NUM, CONCEPT_CD FROM (
SELECT PATIENT_NUM
	, CASE WHEN CONCEPT_CD = '\ACT\Demographics\Age\< 18 years old\' THEN 'DEM|AGE:<18'
	       WHEN CONCEPT_CD = '\ACT\Demographics\Age\>= 18 years old\' THEN 'DEM|AGE:>=18'
		   WHEN CONCEPT_CD = '\ACT\Demographics\Age\>= 65 years old\' THEN 'DEM|AGE:>=65'
		   WHEN CONCEPT_CD = '\ACT\Demographics\Age\>= 85 years old\' THEN 'DEM|AGE:>=85'
		   WHEN CONCEPT_CD = '\ACT\Demographics\Age\>= 90 years old\' THEN 'DEM|AGE:>=90' ELSE CONCEPT_CD END AS CONCEPT_CD
FROM CTE_AGE_TODAY_PATIENT_FACTS
)DEM
WHERE CONCEPT_CD LIKE 'DEM%';

;WITH CTE_AGE_VISIT_PATIENT_FACTS AS (
SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\>= 65 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) >= DATEADD(YY,65,BIRTH_DATE))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\>= 85 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) >= DATEADD(YY,85,BIRTH_DATE))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\>= 90 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) >= DATEADD(YY,90,BIRTH_DATE))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\0-9 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,0,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,10,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\0-9 years old\0 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,0,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,1,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.0' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,0,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,1,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.1' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,1,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,2,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.2' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,2,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,3,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.3' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,3,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,4,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.4' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,4,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,5,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.5' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,5,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,6,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.6' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,6,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,7,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.7' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,7,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,8,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.8' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,8,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,9,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.9' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,9,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,10,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.10' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,10,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,11,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.11' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,11,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,12,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\0-9 years old\1 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,1,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,2,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:0.12' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,12,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,13,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.1' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,13,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,14,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.2' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,14,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,15,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.3' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,15,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,16,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.4' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,16,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,17,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.5' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,17,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,18,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.6' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,18,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,19,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.7' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,19,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,20,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.8' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,20,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,21,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.9' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,21,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,22,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.10' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,22,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,23,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.11' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,23,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,24,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\0-9 years old\2 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,2,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,3,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:1.12' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,24,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,25,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.1' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,25,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,26,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.2' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,26,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,27,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.3' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,27,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,28,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.4' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,28,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,29,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.5' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,29,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,30,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.6' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,30,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,31,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.7' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,31,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,32,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.8' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,32,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,33,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.9' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,33,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,34,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.10' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,34,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,35,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.11' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,35,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,36,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:2.12' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(MM,36,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(MM,37,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:3' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,3,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,4,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:4' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,4,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,5,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:5' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,5,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,6,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:6' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,6,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,7,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:7' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,7,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,8,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:8' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,8,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,9,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:9' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,9,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,10,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\10-17 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,10,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,18,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:10' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,10,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,11,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:11' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,11,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,12,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:12' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,12,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,13,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:13' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,13,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,14,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:14' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,14,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,15,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:15' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,15,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,16,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:16' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,16,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,17,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:17' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,17,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,18,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\18-34 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,18,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,35,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:18' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,18,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,19,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:19' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,19,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,20,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:20' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,20,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,21,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:21' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,21,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,22,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:22' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,22,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,23,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:23' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,23,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,24,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:24' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,24,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,25,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:25' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,25,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,26,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:26' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,26,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,27,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:27' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,27,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,28,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:28' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,28,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,29,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:29' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,29,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,30,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:30' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,30,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,31,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:31' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,31,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,32,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:32' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,32,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,33,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:33' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,33,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,34,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:34' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,34,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,35,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\35-44 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,35,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,45,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:35' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,35,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,36,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:36' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,36,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,37,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:37' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,37,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,38,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:38' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,38,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,39,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:39' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,39,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,40,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:40' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,40,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,41,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:41' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,41,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,42,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:42' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,42,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,43,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:43' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,43,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,44,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:44' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,44,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,45,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\45-54 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,45,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,55,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:45' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,45,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,46,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:46' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,46,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,47,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:47' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,47,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,48,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:48' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,48,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,49,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:49' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,49,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,50,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:50' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,50,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,51,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:51' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,51,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,52,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:52' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,52,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,53,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:53' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,53,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,54,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:54' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,54,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,55,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\55-64 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,55,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,65,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:55' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,55,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,56,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:56' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,56,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,57,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:57' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,57,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,58,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:58' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,58,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,59,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:59' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,59,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,60,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:60' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,60,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,61,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:61' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,61,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,62,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:62' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,62,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,63,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:63' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,63,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,64,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:64' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,64,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,65,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\65-74 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,65,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,75,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:65' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,65,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,66,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:66' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,66,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,67,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:67' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,67,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,68,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:68' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,68,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,69,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:69' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,69,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,70,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:70' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,70,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,71,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:71' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,71,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,72,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:72' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,72,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,73,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:73' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,73,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,74,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:74' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,74,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,75,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\75-84 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,75,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,85,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:75' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,75,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,76,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:76' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,76,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,77,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:77' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,77,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,78,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:78' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,78,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,79,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:79' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,79,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,80,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:80' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,80,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,81,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:81' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,81,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,82,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:82' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,82,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,83,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:83' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,83,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,84,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:84' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,84,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,85,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'\ACT\Visit Details\Age at visit\85-89 years old\' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,85,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,90,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:85' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,85,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,86,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:86' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,86,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,87,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:87' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,87,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,88,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:88' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,88,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,89,BIRTH_DATE)))
UNION SELECT PATIENT_NUM,'VIS|AGE:89' AS CONCEPT_CD FROM VISIT_DIMENSION WHERE PATIENT_NUM IN (SELECT PATIENT_NUM FROM PATIENT_DIMENSION WHERE PATIENT_NUM = VISIT_DIMENSION.PATIENT_NUM AND CONVERT(DATE,VISIT_DIMENSION.START_DATE) BETWEEN DATEADD(YY,89,BIRTH_DATE) AND DATEADD(DD,-1,DATEADD(YY,90,BIRTH_DATE)))
)
INSERT INTO #PV_FACT_PAIRS WITH(TABLOCK)(PATIENT_NUM,CONCEPT_CD)
SELECT DISTINCT PATIENT_NUM, CONCEPT_CD FROM (
SELECT PATIENT_NUM
	, CASE WHEN CONCEPT_CD = '\ACT\Visit Details\Age at visit\>= 65 years old\' THEN 'VIS|AGE:>=65'
	       WHEN CONCEPT_CD = '\ACT\Visit Details\Age at visit\>= 85 years old\' THEN 'VIS|AGE:>=85'
		   WHEN CONCEPT_CD = '\ACT\Visit Details\Age at visit\>= 90 years old\' THEN 'VIS|AGE:>=90' ELSE CONCEPT_CD END AS CONCEPT_CD
FROM CTE_AGE_VISIT_PATIENT_FACTS
)VIS
WHERE CONCEPT_CD LIKE 'VIS%'
;

/* CALCULATE TOTALNUMS */

;WITH CTE_FACT_PAIRS AS (
SELECT PATIENT_NUM, CONCEPT_CD FROM #PV_FACT_PAIRS
UNION ALL
SELECT PATIENT_NUM, CONCEPT_CD FROM OBSFACT_PAIRS
)
INSERT INTO TOTALNUM WITH(TABLOCK) (C_FULLNAME, AGG_COUNT, AGG_DATE, TYPEFLAG_CD)
SELECT DISTINCT OANC.C_FULLNAME, C.AGG_COUNT, CONVERT(DATE, GETDATE()),'PF'
FROM (
SELECT CC_ANCESTOR.ANCESTOR, COUNT(DISTINCT PATIENT_NUM) AGG_COUNT
FROM CONCEPT_CLOSURE CC_ANCESTOR
  JOIN TNUM_ONTOLOGY O
    ON CC_ANCESTOR.DESCENDANT = O.PATH_NUM
  JOIN CTE_FACT_PAIRS F
    ON O.C_BASECODE = F.CONCEPT_CD
GROUP BY CC_ANCESTOR.ANCESTOR
)C
  JOIN TNUM_ONTOLOGY OANC
    ON C.ANCESTOR = OANC.PATH_NUM;

	EXEC EndTime @startime,'all ontologies','counting';
    set @startime = getdate();
	

END;
GO
