INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-1', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-2', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-3', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-4', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-5', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-7', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-8', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo', 'Hospital-6', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo1', 'Hospital-1', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo10', 'Hospital-1', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo10', 'Hospital-3', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo11', 'Hospital-1', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo11', 'Hospital-5', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo11', 'Hospital-6', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo2', 'Hospital-2', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo3', 'Hospital-3', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo4', 'Hospital-4', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo5', 'Hospital-5', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo6', 'Hospital-7', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo7', 'Hospital-8', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo8', 'Hospital-6', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo9', 'Hospital-1', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
INSERT INTO IM_PROJECT_SITES(PROJECT_ID, LCL_SITE, PROJECT_STATUS, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('demo9', 'Hospital-5', 'A', '20130201 11:40:00.0', NULL, NULL, 'DEMO', NULL);
