/*********************************************************
*       SNOWFLAKE SCRIPT TO CREATE ONT CELL TABLES
*       MD SABER HOSSAIN	7/14/2023
*		University of Missouri-Columbia
**********************************************************/
CREATE OR REPLACE SEQUENCE SQ_PROCESS_ID START = 1 INCREMENT = 1; 
CREATE TABLE ONT_PROCESS_STATUS (
    PROCESS_ID			NUMBER(38, 0) NOT NULL DEFAULT SQ_PROCESS_ID.NEXTVAL PRIMARY KEY,
    PROCESS_TYPE_CD		VARCHAR(50),
    START_DATE			timestamp, 
    END_DATE			timestamp,
    PROCESS_STEP_CD		VARCHAR(50),
    PROCESS_STATUS_CD   VARCHAR(50),
    CRC_UPLOAD_ID		INT,
    STATUS_CD			VARCHAR(50),
    MESSAGE				TEXT,
    ENTRY_DATE			timestamp,
    CHANGE_DATE			timestamp,
    CHANGEDBY_CHAR		CHAR(50)
);

CREATE TABLE TOTALNUM_REPORT  ( 
    C_FULLNAME	VARCHAR(850) NULL,
    AGG_DATE  	VARCHAR(50) NULL,
    AGG_COUNT 	int NULL
    )
;

CREATE TABLE TOTALNUM  ( 
    C_FULLNAME	VARCHAR(850) NULL,
    AGG_DATE  	date NULL,
    AGG_COUNT 	int NULL,
    TYPEFLAG_CD   VARCHAR(3) NULL
    )
;

  CREATE TABLE TABLE_ACCESS
   (	C_TABLE_CD VARCHAR(50)	NOT NULL, 
	C_TABLE_NAME VARCHAR(50)	NOT NULL, 
	C_PROTECTED_ACCESS CHAR(1)	NULL,
	C_ONTOLOGY_PROTECTION	TEXT	NULL,
	C_HLEVEL INT				NOT NULL, 
	C_FULLNAME VARCHAR(700)	NOT NULL, 
	C_NAME VARCHAR(2000)		NOT NULL, 
	C_SYNONYM_CD CHAR(1)	NOT NULL, 
	C_VISUALATTRIBUTES CHAR(3)	NOT NULL, 
	C_TOTALNUM INT			NULL, 
	C_BASECODE VARCHAR(50)	NULL, 
	C_METADATAXML TEXT		NULL, 
	C_FACTTABLECOLUMN VARCHAR(50)	NOT NULL, 
	C_DIMTABLENAME VARCHAR(50)	NOT NULL, 
	C_COLUMNNAME VARCHAR(50)	NOT NULL, 
	C_COLUMNDATATYPE VARCHAR(50)	NOT NULL, 
	C_OPERATOR VARCHAR(10)	NOT NULL, 
	C_DIMCODE VARCHAR(700)	NOT NULL, 
	C_COMMENT TEXT	NULL, 
	C_TOOLTIP VARCHAR(900)	NULL, 
	C_ENTRY_DATE timestamp		NULL, 
	C_CHANGE_DATE timestamp	NULL, 
	C_STATUS_CD CHAR(1)		NULL,
	VALUETYPE_CD VARCHAR(50)	NULL
   ) 
   ;


  CREATE TABLE SCHEMES 
   (	C_KEY VARCHAR(50)	 	NOT NULL,
	C_NAME VARCHAR(50)		NOT NULL,
	C_DESCRIPTION VARCHAR(100)	NULL
   ) 
   ;
 