
--------------------------------------------------------
--  DDL for Table I2B2
--------------------------------------------------------

  CREATE TABLE I2B2 
   (	"C_HLEVEL" INT			NOT NULL, 
	"C_FULLNAME" VARCHAR(700)	NOT NULL, 
	"C_NAME" VARCHAR(2000)		NOT NULL, 
	"C_SYNONYM_CD" CHAR(1)		NOT NULL, 
	"C_VISUALATTRIBUTES" CHAR(3)	NOT NULL, 
	"C_TOTALNUM" INT			NULL, 
	"C_BASECODE" VARCHAR(50)	NULL, 
	"C_METADATAXML" VARCHAR(MAX)		NULL, 
	"C_FACTTABLECOLUMN" VARCHAR(50)	NOT NULL, 
	"C_TABLENAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNNAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNDATATYPE" VARCHAR(50)	NOT NULL, 
	"C_OPERATOR" VARCHAR(10)	NOT NULL, 
	"C_DIMCODE" VARCHAR(700)	NOT NULL, 
	"C_COMMENT" VARCHAR(MAX)			NULL, 
	"C_TOOLTIP" VARCHAR(900)	NULL,
	"M_APPLIED_PATH" VARCHAR(700)	NOT NULL, 
	"UPDATE_DATE" DATETIME		NOT NULL, 
	"DOWNLOAD_DATE" DATETIME	NULL, 
	"IMPORT_DATE" DATETIME	NULL, 
	"SOURCESYSTEM_CD" VARCHAR(50)	NULL, 
	"VALUETYPE_CD" VARCHAR(50)	NULL,
	"M_EXCLUSION_CD"	VARCHAR(25) NULL,
	"C_PATH"	VARCHAR(700)   NULL,
	"C_SYMBOL"	VARCHAR(50)	NULL
   ) ;
   
   CREATE INDEX META_FULLNAME_IDX ON I2B2(C_FULLNAME)
;

   CREATE INDEX META_APPLIED_PATH_IDX ON I2B2(M_APPLIED_PATH)
;
   CREATE INDEX META_EXCLUSION_IDX ON I2B2(M_EXCLUSION_CD)
;
   CREATE INDEX META_HLEVEL_IDX ON I2B2(C_HLEVEL)
;
   CREATE INDEX META_SYNONYM_IDX ON I2B2(C_SYNONYM_CD)
;

--------------------------------------------------------
--  DDL for Table BIRN
--------------------------------------------------------

  CREATE TABLE BIRN
   (	"C_HLEVEL" INT			NOT NULL, 
	"C_FULLNAME" VARCHAR(700)	NOT NULL, 
	"C_NAME" VARCHAR(2000)	NOT NULL, 
	"C_SYNONYM_CD" CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES" CHAR(3)	NOT NULL, 
	"C_TOTALNUM" INT			NULL, 
	"C_BASECODE" VARCHAR(50)	NULL, 
	"C_METADATAXML" VARCHAR(MAX)		NULL, 
	"C_FACTTABLECOLUMN" VARCHAR(50)	NOT NULL, 
	"C_TABLENAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNNAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNDATATYPE" VARCHAR(50)	NOT NULL, 
	"C_OPERATOR" VARCHAR(10)	NOT NULL, 
	"C_DIMCODE" VARCHAR(700)	NOT NULL, 
	"C_COMMENT" VARCHAR(MAX)			NULL, 
	"C_TOOLTIP" VARCHAR(900)	NULL, 
	"M_APPLIED_PATH" VARCHAR(700)	NOT NULL, 
	"UPDATE_DATE" DATETIME		NOT NULL, 
	"DOWNLOAD_DATE" DATETIME	NULL, 
	"IMPORT_DATE" DATETIME		NULL, 
	"SOURCESYSTEM_CD" VARCHAR(50)	NULL, 
	"VALUETYPE_CD" VARCHAR(50)	NULL,
	"M_EXCLUSION_CD"	VARCHAR(25) NULL,
	"C_PATH"	VARCHAR(700)   NULL,
	"C_SYMBOL"	VARCHAR(50)	NULL
   ) ;
 
    CREATE INDEX META_FULLNAME_IDX ON BIRN(C_FULLNAME)
;

   CREATE INDEX META_APPLIED_PATH_IDX ON BIRN(M_APPLIED_PATH)
;
--------------------------------------------------------
--  DDL for Table SCHEMES
--------------------------------------------------------

  CREATE TABLE SCHEMES 
   (	"C_KEY" VARCHAR(50)	 	NOT NULL,
	"C_NAME" VARCHAR(50)		NOT NULL,
	"C_DESCRIPTION" VARCHAR(100)	NULL,
	 CONSTRAINT SCHEMES_PK PRIMARY KEY(C_KEY)
   ) ;
 
--------------------------------------------------------
--  DDL for Table TABLE_ACCESS
--------------------------------------------------------

  CREATE TABLE TABLE_ACCESS
   (	"C_TABLE_CD" VARCHAR(50)	NOT NULL, 
	"C_TABLE_NAME" VARCHAR(50)	NOT NULL, 
	"C_PROTECTED_ACCESS" CHAR(1)	NULL,
	"C_ONTOLOGY_PROTECTION"	VARCHAR(MAX)	NULL,	
	"C_HLEVEL" INT				NOT NULL, 
	"C_FULLNAME" VARCHAR(700)	NOT NULL, 
	"C_NAME" VARCHAR(2000)		NOT NULL, 
	"C_SYNONYM_CD" CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES" CHAR(3)	NOT NULL, 
	"C_TOTALNUM" INT			NULL, 
	"C_BASECODE" VARCHAR(50)	NULL, 
	"C_METADATAXML" VARCHAR(MAX)		NULL, 
	"C_FACTTABLECOLUMN" VARCHAR(50)	NOT NULL, 
	"C_DIMTABLENAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNNAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNDATATYPE" VARCHAR(50)	NOT NULL, 
	"C_OPERATOR" VARCHAR(10)	NOT NULL, 
	"C_DIMCODE" VARCHAR(700)	NOT NULL, 
	"C_COMMENT" VARCHAR(MAX)	NULL, 
	"C_TOOLTIP" VARCHAR(900)	NULL, 
	"C_ENTRY_DATE" DATETIME		NULL, 
	"C_CHANGE_DATE" DATETIME	NULL, 
	"C_STATUS_CD" CHAR(1)		NULL,
	"VALUETYPE_CD" VARCHAR(50)	NULL,
   ) ;
 
--------------------------------------------------------
--  DDL for Table CUSTOM_META
--------------------------------------------------------

	CREATE TABLE CUSTOM_META
   (	"C_HLEVEL" INT			NOT NULL, 
	"C_FULLNAME" VARCHAR(700)	NOT NULL, 
	"C_NAME" VARCHAR(2000)		NOT NULL, 
	"C_SYNONYM_CD" CHAR(1)		NOT NULL, 
	"C_VISUALATTRIBUTES" CHAR(3)	NOT NULL, 
	"C_TOTALNUM" INT			NULL, 
	"C_BASECODE" VARCHAR(50)	NULL, 
	"C_METADATAXML" VARCHAR(MAX)		NULL, 
	"C_FACTTABLECOLUMN" VARCHAR(50)	NOT NULL, 
	"C_TABLENAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNNAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNDATATYPE" VARCHAR(50)	NOT NULL, 
	"C_OPERATOR" VARCHAR(10)	NOT NULL, 
	"C_DIMCODE" VARCHAR(700)	NOT NULL, 
	"C_COMMENT" VARCHAR(MAX)			NULL, 
	"C_TOOLTIP" VARCHAR(900)	NULL, 
	"M_APPLIED_PATH" VARCHAR(700)	NOT NULL, 
	"UPDATE_DATE" DATETIME		NOT NULL, 
	"DOWNLOAD_DATE" DATETIME	NULL, 
	"IMPORT_DATE" DATETIME	NULL, 
	"SOURCESYSTEM_CD" VARCHAR(50)	NULL, 
	"VALUETYPE_CD" VARCHAR(50)	NULL,
	"M_EXCLUSION_CD"	VARCHAR(25) NULL,
	"C_PATH"	VARCHAR(700)   NULL,
	"C_SYMBOL"	VARCHAR(50)	NULL
   ) ;

   CREATE INDEX META_FULLNAME_IDX ON CUSTOM_META(C_FULLNAME)
;

   CREATE INDEX META_APPLIED_PATH_IDX ON CUSTOM_META(M_APPLIED_PATH)
;

 --------------------------------------------------------
--  DDL for Table ONT_PROCESS_STATUS
--------------------------------------------------------
	
CREATE TABLE ONT_PROCESS_STATUS (
    PROCESS_ID			INT IDENTITY(1,1) PRIMARY KEY, 
    PROCESS_TYPE_CD		VARCHAR(50),
    START_DATE			DATETIME, 
    END_DATE			DATETIME,
    PROCESS_STEP_CD		VARCHAR(50),
    PROCESS_STATUS_CD   VARCHAR(50),
    CRC_UPLOAD_ID		INT,
    STATUS_CD			VARCHAR(50),
    MESSAGE				VARCHAR(MAX),
    ENTRY_DATE			DATETIME,
    CHANGE_DATE			DATETIME,
    CHANGEDBY_CHAR		CHAR(50)
);

 CREATE TABLE ICD10_ICD9
   (	"C_HLEVEL" INT			NOT NULL, 
	"C_FULLNAME" VARCHAR(700)	NOT NULL, 
	"C_NAME" VARCHAR(2000)		NOT NULL, 
	"C_SYNONYM_CD" CHAR(1)		NOT NULL, 
	"C_VISUALATTRIBUTES" CHAR(3)	NOT NULL, 
	"C_TOTALNUM" INT			NULL, 
	"C_BASECODE" VARCHAR(50)	NULL, 
	"C_METADATAXML" VARCHAR(MAX)		NULL, 
	"C_FACTTABLECOLUMN" VARCHAR(50)	NOT NULL, 
	"C_TABLENAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNNAME" VARCHAR(50)	NOT NULL, 
	"C_COLUMNDATATYPE" VARCHAR(50)	NOT NULL, 
	"C_OPERATOR" VARCHAR(10)	NOT NULL, 
	"C_DIMCODE" VARCHAR(700)	NOT NULL, 
	"C_COMMENT" VARCHAR(MAX)			NULL, 
	"C_TOOLTIP" VARCHAR(900)	NULL,
	"M_APPLIED_PATH" VARCHAR(700)	NOT NULL, 
	"UPDATE_DATE" DATETIME		NOT NULL, 
	"DOWNLOAD_DATE" DATETIME	NULL, 
	"IMPORT_DATE" DATETIME	NULL, 
	"SOURCESYSTEM_CD" VARCHAR(50)	NULL, 
	"VALUETYPE_CD" VARCHAR(50)	NULL,
	"M_EXCLUSION_CD"	VARCHAR(25) NULL,
	"C_PATH"	VARCHAR(700)   NULL,
	"C_SYMBOL"	VARCHAR(50)	NULL,
	"PLAIN_CODE" VARCHAR(25) NULL
   ) ;
  CREATE INDEX META_FULLNAME_ICD10_IDX ON ICD10_ICD9(C_FULLNAME)
;
  CREATE INDEX META_APPL_PATH_ICD10_IDX ON ICD10_ICD9(M_APPLIED_PATH)
;
  CREATE INDEX META_EXCLUSION_ICD10_IDX ON ICD10_ICD9(M_EXCLUSION_CD)
;
  CREATE INDEX META_HLEVEL_ICD10_IDX ON ICD10_ICD9(C_HLEVEL)
;
  CREATE INDEX META_SYNONYM_ICD10_IDX ON ICD10_ICD9(C_SYNONYM_CD)
;

 --------------------------------------------------------
--  DDL for totalnum table to track counts over time
--------------------------------------------------------

-- New 04-20: Create totalnum table to track changes over time
CREATE TABLE [totalnum]  ( 
    [c_fullname]	varchar(850) NULL,
    [agg_date]  	datetime NULL,
    [agg_count] 	int NULL,
    [typeflag_cd]   varchar(3) NULL
    );
CREATE INDEX totalnum_idx ON totalnum([c_fullname], [agg_date], [typeflag_cd]);

-- Report table to store most recent obfuscated counts
CREATE TABLE [totalnum_report]  ( 
    [c_fullname]	varchar(850) NULL,
    [agg_date]  	varchar(50) NULL,
    [agg_count] 	int NULL
    );
CREATE INDEX totalnum_report_idx ON totalnum_report([c_fullname]);

