INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(1, '\i2b2\Reports\', 'Reports', 'N', 'FA ', NULL, 'LCS-I2B2:REPORTS', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-12-19T13:32:16.198-04:00</CreationDateTime><TestID>LCS-I2B2:REPORTS</TestID><TestName>Reports</TestName><DataType>largestring</DataType><MaxStringLength/><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\', NULL, 'i2b2 \ Reports', '20100505 00:00:00.0', '20100505 00:00:00.0', '20100505 00:00:00.0', 'Demo', NULL, '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\CT Reports\', 'CT Reports', 'N', 'LAE', NULL, 'LCS-I2B2:CT_RPT', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\CT Reports\', NULL, 'i2b2 \ Reports \ CT Reports', '20100505 00:00:00.0', '20100505 00:00:00.0', '20100505 00:00:00.0', 'Demo', 'DOC', '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\MRI Reports\', 'MRI Reports', 'N', 'LAE', NULL, 'LCS-I2B2:MRI_RPT', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\MRI Reports\', NULL, 'i2b2 \ Reports \ MRI Reports', '20100505 00:00:00.0', '20100505 00:00:00.0', '20100505 00:00:00.0', 'Demo', 'DOC', '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\X-Ray Reports\', 'X-Ray Reports', 'N', 'LAE', NULL, 'LCS-I2B2:XR_RPT', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\X-Ray Reports\', NULL, 'i2b2 \ Reports \ X-Ray Reports', '20100505 00:00:00.0', '20100505 00:00:00.0', '20100505 00:00:00.0', 'Demo', 'DOC', '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\Medical History\', 'Medical history', 'N', 'FA ', NULL, 'LCS-I2B2:MH', NULL, 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\Medical History\', NULL, 'i2b2 \ Reports \ Medical History', '20111101 13:31:43.0', NULL, NULL, 'DEMO', NULL, '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(3, '\i2b2\Reports\Medical History\Family History\', 'Family history', 'N', 'LA ', NULL, 'LCS-I2B2:FH', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-10-19T13:32:16.198-04:00</CreationDateTime><TestID>LCS-I2B2:FH</TestID><TestName>Family History</TestName><DataType>String</DataType><MaxStringLength>50</MaxStringLength><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\Medical History\Family History\', NULL, 'i2b2 \ Reports \ Medical History \ Family History', '20111101 13:31:43.0', NULL, NULL, 'DEMO', NULL, '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(3, '\i2b2\Reports\Medical History\Social History\', 'Social history', 'N', 'LA ', NULL, 'LCS-I2B2:SH', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-10-19T13:32:16.198-04:00</CreationDateTime><TestID>LCS-I2B2:SH</TestID><TestName>Social History</TestName><DataType>String</DataType><MaxStringLength>50</MaxStringLength><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\Medical History\Social History\', NULL, 'i2b2 \ Reports \ Medical History \ Social History', '20111101 13:31:43.0', NULL, NULL, 'DEMO', NULL, '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\De-Identified CT Reports\', 'De-Identified CT Reports', 'N', 'LAE', NULL, 'LCS-I2B2:CT_RPT_DID', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-12-19T13:32:16.198-04:00</CreationDateTime><TestID>LCS-I2B2:CT_RPT_DID</TestID><TestName>De-Identified CT Reports</TestName><DataType>largestring</DataType><MaxStringLength/><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\De-Identified CT Reports\', '', '\ i2b2 \ Reports \ De-Identified CT Reports \', '20111219 00:00:00.0', '20111219 00:00:00.0', '20111219 00:00:00.0', 'Demo', 'DOC', '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\De-Identified MRI Reports\', 'De-Identified MRI Reports', 'N', 'LA', NULL, 'LCS-I2B2:MRI_RPT_DID', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-12-19T13:32:16.198-04:00</CreationDateTime><TestID>LCS-I2B2:MRI_RPT_DID</TestID><TestName>De-Identified MRI Reports</TestName><DataType>largestring</DataType><MaxStringLength/><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\De-Identified MRI Reports\', '', '\ i2b2 \ Reports \ De-Identified MRI Reports \', '20111219 00:00:00.0', '20111219 00:00:00.0', '20111219 00:00:00.0', 'Demo', 'DOC', '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\De-Identified X-Ray Reports\', 'De-Identified X-Ray Reports', 'N', 'LA', NULL, 'LCS-I2B2:XR_RPT_DID', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2011-12-19T13:32:16.198-04:00</CreationDateTime><TestID>LCS-I2B2:XR_RPT_DID</TestID><TestName>De-Identified X-Ray Reports</TestName><DataType>largestring</DataType><MaxStringLength/><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\De-Identified X-Ray Reports\', '', '\ i2b2 \ Reports \ De-Identified X-Ray Reports \', '20111219 00:00:00.0', '20111219 00:00:00.0', '20111219 00:00:00.0', 'Demo', 'DOC', '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(2, '\i2b2\Reports\Visit Notes\', 'Visit Notes', 'N', 'FA', NULL, 'LCS-I2B2:VN', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2012-03-08T09:25:15.198-04:00</CreationDateTime><TestID>LCS-I2B2:VN</TestID><TestName>Visit Notes</TestName><DataType>largestring</DataType><MaxStringLength/><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\Visit Notes\', '', '\ i2b2 \ Reports \ Visit Notes \', '20120308 00:00:00.0', '20120308 00:00:00.0', '20120308 00:00:00.0', 'Demo', 'DOC', '@', NULL);
INSERT INTO I2B2(C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_TABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, VALUETYPE_CD, M_APPLIED_PATH, M_EXCLUSION_CD)
  VALUES(3, '\i2b2\Reports\Visit Notes\Consultations\', 'Consultations', 'N', 'LA', NULL, 'LCS-I2B2:CONSULT', '<?xml version="1.0" encoding="UTF-8"?><ValueMetadata><Version>3.2</Version><CreationDateTime>2012-03-08T09:25:15.198-04:00</CreationDateTime><TestID>LCS-I2B2:CONSULT</TestID><TestName>Consultation</TestName><DataType>largestring</DataType><MaxStringLength/><Flagstouse/><Oktousevalues/></ValueMetadata>', 'concept_cd', 'concept_dimension', 'concept_path', 'T', 'LIKE', '\i2b2\Reports\Visit Notes\Consultations\', '', '\ i2b2 \ Reports \ Visit Notes \ Consultations \', '20120308 00:00:00.0', '20120308 00:00:00.0', '20120308 00:00:00.0', 'Demo', 'DOC', '@', NULL);
