
--------------------------------------------------------
--  DDL for Table I2B2
--------------------------------------------------------

CREATE TABLE I2B2 (
	"C_HLEVEL"				NUMBER(22,0)	NOT NULL, 
	"C_FULLNAME"			VARCHAR2(700)	NOT NULL, 
	"C_NAME"				VARCHAR2(2000)	NOT NULL, 
	"C_SYNONYM_CD"			CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES"	CHAR(3)	NOT NULL, 
	"C_TOTALNUM"			NUMBER(22,0)	NULL, 
	"C_BASECODE"			VARCHAR2(50)	NULL, 
	"C_METADATAXML"			CLOB	NULL, 
	"C_FACTTABLECOLUMN"		VARCHAR2(50)	NOT NULL, 
	"C_TABLENAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNNAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNDATATYPE"		VARCHAR2(50)	NOT NULL, 
	"C_OPERATOR"			VARCHAR2(10)	NOT NULL, 
	"C_DIMCODE"				VARCHAR2(700)	NOT NULL, 
	"C_COMMENT"				CLOB	NULL, 
	"C_TOOLTIP"				VARCHAR2(900)	NULL, 
	"M_APPLIED_PATH"		VARCHAR2(700)	NOT NULL, 
	"UPDATE_DATE"			DATE	NOT NULL, 
	"DOWNLOAD_DATE"			DATE	NULL, 
	"IMPORT_DATE"			DATE	NULL, 
	"SOURCESYSTEM_CD"		VARCHAR2(50)	NULL, 
	"VALUETYPE_CD"			VARCHAR2(50)	NULL,
	"M_EXCLUSION_CD"			VARCHAR2(25) NULL,
	"C_PATH"				VARCHAR2(700)   NULL,
	"C_SYMBOL"				VARCHAR2(50)	NULL
)
;
CREATE INDEX META_FULLNAME_I2B2_IDX ON I2B2(C_FULLNAME)
;
CREATE INDEX META_APPLIED_PATH_I2B2_IDX ON I2B2(M_APPLIED_PATH)
;
CREATE INDEX META_EXCLUSION_I2B2_IDX ON I2B2(M_EXCLUSION_CD)
;
CREATE INDEX META_HLEVEL_I2B2_IDX ON I2B2(C_HLEVEL)
;
CREATE INDEX META_SYNONYM_I2B2_IDX ON I2B2(C_SYNONYM_CD)
;

--------------------------------------------------------
--  DDL for Table BIRN
--------------------------------------------------------

CREATE TABLE BIRN (
	"C_HLEVEL"				NUMBER(22,0)	NOT NULL, 
	"C_FULLNAME"			VARCHAR2(700)	NOT NULL, 
	"C_NAME"				VARCHAR2(2000)	NOT NULL, 
	"C_SYNONYM_CD"			CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES"	CHAR(3)	NOT NULL, 
	"C_TOTALNUM"			NUMBER(22,0)	NULL, 
	"C_BASECODE"			VARCHAR2(50)	NULL, 
	"C_METADATAXML"			CLOB	NULL, 
	"C_FACTTABLECOLUMN"		VARCHAR2(50)	NOT NULL, 
	"C_TABLENAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNNAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNDATATYPE"		VARCHAR2(50)	NOT NULL, 
	"C_OPERATOR"			VARCHAR2(10)	NOT NULL, 
	"C_DIMCODE"				VARCHAR2(700)	NOT NULL, 
	"C_COMMENT"				CLOB	NULL, 
	"C_TOOLTIP"				VARCHAR2(900)	NULL, 
	"M_APPLIED_PATH"		VARCHAR2(700)	NOT NULL, 
	"UPDATE_DATE"			DATE	NOT NULL, 
	"DOWNLOAD_DATE"			DATE	NULL, 
	"IMPORT_DATE"			DATE	NULL, 
	"SOURCESYSTEM_CD"		VARCHAR2(50)	NULL, 
	"VALUETYPE_CD"			VARCHAR2(50)	NULL,
	"M_EXCLUSION_CD"			VARCHAR2(25) NULL,
	"C_PATH"				VARCHAR2(700)   NULL,
	"C_SYMBOL"				VARCHAR2(50)	NULL
)
;
CREATE INDEX META_FULLNAME_BIRN_IDX ON BIRN(C_FULLNAME)
;
CREATE INDEX META_APPLIED_PATH_BIRN_IDX ON BIRN(M_APPLIED_PATH)
;

--------------------------------------------------------
--  DDL for Table SCHEMES
--------------------------------------------------------

CREATE TABLE SCHEMES (
   	"C_KEY"			VARCHAR2(50) NOT NULL,
	"C_NAME"		VARCHAR2(50)	NOT NULL,
	"C_DESCRIPTION"	VARCHAR2(100)	NULL,
	 CONSTRAINT SCHEMES_PK PRIMARY KEY(C_KEY)
)
;


--------------------------------------------------------
--  DDL for Table TABLE_ACCESS
--------------------------------------------------------

CREATE TABLE TABLE_ACCESS (
	"C_TABLE_CD"			VARCHAR2(50)	NOT NULL, 
	"C_TABLE_NAME"			VARCHAR2(50)	NOT NULL, 
	"C_PROTECTED_ACCESS"	CHAR(1)	NULL,
	"C_ONTOLOGY_PROTECTION"	CLOB	NULL,
	"C_HLEVEL"				NUMBER(22,0)	NOT NULL, 
	"C_FULLNAME"			VARCHAR2(700)	NOT NULL, 
	"C_NAME"				VARCHAR2(2000)		NOT NULL, 
	"C_SYNONYM_CD"			CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES"	CHAR(3)	NOT NULL, 
	"C_TOTALNUM"			NUMBER(22,0)	NULL, 
	"C_BASECODE"			VARCHAR2(50)	NULL, 
	"C_METADATAXML"			CLOB	NULL, 
	"C_FACTTABLECOLUMN"		VARCHAR2(50)	NOT NULL, 
	"C_DIMTABLENAME"		VARCHAR2(50)	NOT NULL, 
	"C_COLUMNNAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNDATATYPE"		VARCHAR2(50)	NOT NULL, 
	"C_OPERATOR"			VARCHAR2(10)	NOT NULL, 
	"C_DIMCODE"				VARCHAR2(700)	NOT NULL, 
	"C_COMMENT"				CLOB	NULL, 
	"C_TOOLTIP"				VARCHAR2(900)	NULL, 
	"C_ENTRY_DATE"			DATE	NULL, 
	"C_CHANGE_DATE"			DATE	NULL, 
	"C_STATUS_CD"			CHAR(1)	NULL,
	"VALUETYPE_CD"			VARCHAR2(50)	NULL
	)
;


--------------------------------------------------------
--  DDL for Table CUSTOM_META
--------------------------------------------------------

CREATE TABLE CUSTOM_META ( 
	"C_HLEVEL"				NUMBER(22,0)	NOT NULL, 
	"C_FULLNAME"			VARCHAR2(700)	NOT NULL, 
	"C_NAME"				VARCHAR2(2000)	NOT NULL, 
	"C_SYNONYM_CD"			CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES"	CHAR(3)	NOT NULL, 
	"C_TOTALNUM"			NUMBER(22,0)	NULL, 
	"C_BASECODE"			VARCHAR2(50)	NULL, 
	"C_METADATAXML"			CLOB	NULL, 
	"C_FACTTABLECOLUMN"		VARCHAR2(50)	NOT NULL, 
	"C_TABLENAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNNAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNDATATYPE"		VARCHAR2(50)	NOT NULL, 
	"C_OPERATOR"			VARCHAR2(10)	NOT NULL, 
	"C_DIMCODE"				VARCHAR2(700)	NOT NULL, 
	"C_COMMENT"				CLOB	NULL, 
	"C_TOOLTIP"				VARCHAR2(900)	NULL, 
	"M_APPLIED_PATH"		VARCHAR2(700)	NOT NULL, 
	"UPDATE_DATE"			DATE	NOT NULL, 
	"DOWNLOAD_DATE"			DATE	NULL, 
	"IMPORT_DATE"			DATE	NULL, 
	"SOURCESYSTEM_CD"		VARCHAR2(50)	NULL, 
	"VALUETYPE_CD"			VARCHAR2(50)	NULL,
	"M_EXCLUSION_CD"			VARCHAR2(25) NULL,
	"C_PATH"				VARCHAR2(700)   NULL,
	"C_SYMBOL"				VARCHAR2(50)	NULL
)
;

CREATE INDEX META_FULLNAME_CUSTOM_IDX ON CUSTOM_META(C_FULLNAME)
;
CREATE INDEX META_APPLIED_PATH_CUSTOM_IDX ON CUSTOM_META(M_APPLIED_PATH)
;

--------------------------------------------------------
--  DDL for Table ONT_PROCESS_STATUS
--------------------------------------------------------
	
CREATE TABLE ONT_PROCESS_STATUS (
    PROCESS_ID			NUMBER(5,0) PRIMARY KEY, 
    PROCESS_TYPE_CD		VARCHAR(50),
    START_DATE			DATE, 
    END_DATE			DATE,
    PROCESS_STEP_CD		VARCHAR2(50),
    PROCESS_STATUS_CD   VARCHAR2(50),
    CRC_UPLOAD_ID		NUMBER(38,0),
    STATUS_CD			VARCHAR2(50),
    MESSAGE			CLOB,
    ENTRY_DATE			DATE,
    CHANGE_DATE			DATE,
    CHANGEDBY_CHAR		CHAR(50)
)
;

create sequence ONT_SQ_PS_PRID start with 1
; 

CREATE TABLE ICD10_ICD9 (
	"C_HLEVEL"				NUMBER(22,0)	NOT NULL, 
	"C_FULLNAME"			VARCHAR2(700)	NOT NULL, 
	"C_NAME"				VARCHAR2(2000)	NOT NULL, 
	"C_SYNONYM_CD"			CHAR(1)	NOT NULL, 
	"C_VISUALATTRIBUTES"	CHAR(3)	NOT NULL, 
	"C_TOTALNUM"			NUMBER(22,0)	NULL, 
	"C_BASECODE"			VARCHAR2(50)	NULL, 
	"C_METADATAXML"			CLOB	NULL, 
	"C_FACTTABLECOLUMN"		VARCHAR2(50)	NOT NULL, 
	"C_TABLENAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNNAME"			VARCHAR2(50)	NOT NULL, 
	"C_COLUMNDATATYPE"		VARCHAR2(50)	NOT NULL, 
	"C_OPERATOR"			VARCHAR2(10)	NOT NULL, 
	"C_DIMCODE"				VARCHAR2(700)	NOT NULL, 
	"C_COMMENT"				CLOB	NULL, 
	"C_TOOLTIP"				VARCHAR2(900)	NULL, 
	"M_APPLIED_PATH"		VARCHAR2(700)	NOT NULL, 
	"UPDATE_DATE"			DATE	NOT NULL, 
	"DOWNLOAD_DATE"			DATE	NULL, 
	"IMPORT_DATE"			DATE	NULL, 
	"SOURCESYSTEM_CD"		VARCHAR2(50)	NULL, 
	"VALUETYPE_CD"			VARCHAR2(50)	NULL,
	"M_EXCLUSION_CD"			VARCHAR2(25) NULL,
	"C_PATH"				VARCHAR2(700)   NULL,
	"C_SYMBOL"				VARCHAR2(50)	NULL,
	"PLAIN_CODE"			VARCHAR(25)		NULL
)
;
CREATE INDEX META_FULLNAME_ICD10_ICD9_IDX ON ICD10_ICD9(C_FULLNAME)
;
CREATE INDEX META_APPL_PATH_ICD10_ICD9_IDX ON ICD10_ICD9(M_APPLIED_PATH)
; 
CREATE INDEX META_EXCLUSION_ICD19_ICD9_IDX ON ICD10_ICD9(M_EXCLUSION_CD)
;
CREATE INDEX META_HLEVEL_ICD10_ICD9_IDX ON ICD10_ICD9(C_HLEVEL)
;
CREATE INDEX META_SYNONYM_ICD10_ICD9_IDX ON ICD10_ICD9(C_SYNONYM_CD)
;

 --------------------------------------------------------
--  DDL for totalnum table to track counts over time
--------------------------------------------------------

-- New 04-20: Create totalnum table to track changes over time
CREATE TABLE totalnum  ( 
    C_FULLNAME	varchar2(850) NULL,
    AGG_DATE  	date NULL,
    AGG_COUNT 	NUMBER(22,0) NULL,
    TYPEFLAG_CD   varchar2(3) NULL
    )
;
CREATE INDEX totalnum_idx ON totalnum(c_fullname, agg_date, typeflag_cd)
;

-- Report table to store most recent obfuscated counts
CREATE TABLE totalnum_report  ( 
    C_FULLNAME	varchar2(850) NULL,
    AGG_DATE  	date NULL,
    AGG_COUNT 	NUMBER(22,0) NULL
    )
;
CREATE INDEX totalnum_report_idx ON totalnum(c_fullname)
;
