INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\0\', 'TNM:STAGE0', 'Carcinoma in situ', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\I\', 'TNM:STAGEI', 'Cancer is localized', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\II\', 'TNM:STAGEII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\III\', 'TNM:STAGEIII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\IV\', 'TNM:STAGEIV', 'Metastasized to distant lymph nodes and / organs', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\', 'TNM:TUMOR', 'TNM Staging, Tumor Rating', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T0\', 'TNM:T0', 'No evidence of primary tumor', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T1\', 'TNM:T1', 'Tumor small in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T2\', 'TNM:T2', 'Tumor medium in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T3\', 'TNM:T3', 'Tumor large in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T4\', 'TNM:T4', 'Tumor very large in size', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\Tis\', 'TNM:Tis', 'Carcinoma in situ', 'CIS; abnormal cells present but have not spread to neighboring tissue.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\TX\', 'TNM:TX', 'Primary tumor cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Admit Diagnosis\', '0', 'Admit Diagnosis', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\', 'TNM:METASTISIS', 'TNM Staging, Distant Metastisis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M0\', 'TNM:M0', 'TNM Staging, No distant metastasis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M1\', 'TNM:M1', 'TNM Staging, Distant metastasis is present', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M1\M1a\', 'TNM:M1a', 'TNM Staging, Metastasized to other lung; Malignant pleural effusion; or Malignant pericardial effusion', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M1\M1b\', 'TNM:M1b', 'TNM Staging, Metastasized to distant lymph nodes and / organs', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\', 'TNM:NODES', 'TNM Staging, Regional lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N0\', 'TNM:N0', 'TNM Staging, No regional lymph node involvement', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N1\', 'TNM:N1', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes within the lung and/or the hilar lymph nodes. Affected lymph nodes are on the same side as the primary tumor.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N2\', 'TNM:N2', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes around the carina or in the mediastinum. Affected lymph nodes are on the same side as the primary tumor.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N3\', 'TNM:N3', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes near the collarbone on either side, and/or spread to hilar or mediastinal lymph nodes on the side opposite the primary tumor', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\NX\', 'TNM:NX', 'TNM Staging, Regional lymph nodes cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\', 'TNM:STAGE', 'TNM Staging, Stage Classification', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\0\', 'TNM:STAGE0', 'Carcinoma in situ', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\I\', 'TNM:STAGEI', 'Cancer is localized', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\I\IA\', 'TNM:STAGEIA', 'Cancer is localized; tumor is no larger than 3 cm; No involvement of lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\I\IB\', 'TNM:STAGEIB', 'Cancer is localized; tumor is between 3 and 5 cm; No involvement of lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\II\', 'TNM:STAGEII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\II\IIA\', 'TNM:STAGEIIA', 'Cancer is localized; tumor is greater than 3 cm; Local lymph nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\II\IIB\', 'TNM:STAGEIIB', 'Cancer is localized; tumor is greater than 5 cm; Local lymph nodes may be involved; Multiple nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\III\', 'TNM:STAGEIII', 'Cancer is localized, advanced within area', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\III\IIB\', 'TNM:STAGEIIIB', 'Cancer is localized;  tumor may have grown into surrounding structures; Regional lymph nodes may be involved; Multiple nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\III\IIIA\', 'TNM:STAGEIIIA', 'Cancer is localized; tumor may have grown into surrounding structures; Regional lymph nodes may be involved', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\IV\', 'TNM:STAGEIV', 'Metastasized to distant lymph nodes and / organs', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\Occult\', 'TNM:STAGE0', 'Cancer found in lung fluids but its location can''t be determined', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\', 'TNM:TUMOR', 'TNM Staging, Tumor Rating', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T0\', 'TNM:T0', 'No evidence of primary tumor', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T1\', 'TNM:T1', 'Tumor no greater than 3 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T1\T1a\', 'TNM:T1a', 'Tumor no greater than 2 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T1\T1b\', 'TNM:T1b', 'Tumor greater than 2 cm but less than 3 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T2\', 'TNM:T2', 'Tumor between 3  and 7 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T2\T2a\', 'TNM:T2a', 'Tumor no greater than 5 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T2\T2b\', 'TNM:T2b', 'Tumor greater than 5 cm but less than 7 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T3\', 'TNM:T3', 'Tumor greater than 7 cm', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T4\', 'TNM:T4', 'Tumor grown into other areas or multiple nodules', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\Tis\', 'TNM:Tis', 'Carcinoma in situ', 'CIS; abnormal cells present but have not spread to neighboring tissue.', TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\TX\', 'TNM:TX', 'Primary tumor cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Medication\Dose\', 'MED:DOSE', 'Dose', NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Medication\Frequency\', 'MED:FREQ', 'Frequency', NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Medication\Route\', 'MED:ROUTE', 'Route', NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-03-31 09:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Principal Diagnosis\', '1', 'Principal Diagnosis', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Secondary Diagnosis\', '2', 'Secondary Diagnosis', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Mild To Mod\', 'SNO:371923003', 'Mild to moderate', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Mild\', 'SNO:255604002', 'Mild', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Moderate To Severe\', 'SNO:371924009', 'Moderate to severe', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Moderate\', 'SNO:6736007', 'Moderate', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Severe\', 'SNO:24484000', 'Severe', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Severe\Fatal\', 'SNO:399166001', 'Fatal', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Severe\Type I Hypersensitivity\', 'SNO:264774001', 'Type I Hypersensitivity', NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-14 00:55:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\', 'TNM:METASTISIS', 'TNM Staging, Distant Metastisis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\M0\', 'TNM:M0', 'TNM Staging, No distant metastasis', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\M1\', 'TNM:M1', 'TNM Staging, Distant metastasis is present', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\MX\', 'TNM:MX', 'TNM Staging, Distant metastasis cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\', 'TNM:NODES', 'TNM Staging, Regional lymph nodes', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N0\', 'TNM:N0', 'TNM Staging, No regional lymph node involvement', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N1\', 'TNM:N1', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N2\', 'TNM:N2', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N3\', 'TNM:N3', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\NX\', 'TNM:NX', 'TNM Staging, Regional lymph nodes cannot be evaluated', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\', 'TNM:STAGE', 'TNM Staging, Stage Classification', NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), NULL, TO_DATE('2011-04-15 00:10:00','YYYY-MM-DD HH24:MI:SS'), 'DEMO', NULL);
INSERT INTO modifier_dimension(modifier_path, modifier_cd, name_char, modifier_blob, update_date, download_date, import_date, sourcesystem_cd, UPLOAD_ID)
  VALUES('\Medication\RxSig\', 'MED:SIG', 'Rx Sig', '', TO_DATE('01/11/2011 12:00:00 AM', 'DD/MM/YYYY HH12:MI:SS PM'), NULL, TO_DATE('01/11/2011 12:00:00 AM', 'DD/MM/YYYY HH12:MI:SS PM'), 'DEMO', NULL);
INSERT INTO modifier_dimension(modifier_path, modifier_cd, name_char, modifier_blob, update_date, download_date, import_date, sourcesystem_cd, UPLOAD_ID)
  VALUES('\Medication\Instructions\', 'MED:INST', 'Patient Instructions', '', TO_DATE('01/11/2011 12:00:00 AM', 'DD/MM/YYYY HH12:MI:SS PM'), NULL, TO_DATE('01/11/2011 12:00:00 AM', 'DD/MM/YYYY HH12:MI:SS PM'), 'DEMO', NULL);
