INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Admit Diagnosis\', '0', 'Admit Diagnosis', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\', 'TNM:METASTISIS', 'TNM Staging, Distant Metastisis', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M0\', 'TNM:M0', 'TNM Staging, No distant metastasis', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M1\', 'TNM:M1', 'TNM Staging, Distant metastasis is present', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M1\M1a\', 'TNM:M1a', 'TNM Staging, Metastasized to other lung; Malignant pleural effusion; or Malignant pericardial effusion', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Metastisis\M1\M1b\', 'TNM:M1b', 'TNM Staging, Metastasized to distant lymph nodes and / organs', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\', 'TNM:NODES', 'TNM Staging, Regional lymph nodes', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N0\', 'TNM:N0', 'TNM Staging, No regional lymph node involvement', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N1\', 'TNM:N1', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes within the lung and/or the hilar lymph nodes. Affected lymph nodes are on the same side as the primary tumor.', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N2\', 'TNM:N2', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes around the carina or in the mediastinum. Affected lymph nodes are on the same side as the primary tumor.', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\N3\', 'TNM:N3', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', 'Involves lymph nodes near the collarbone on either side, and/or spread to hilar or mediastinal lymph nodes on the side opposite the primary tumor', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Nodes\NX\', 'TNM:NX', 'TNM Staging, Regional lymph nodes cannot be evaluated', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\', 'TNM:STAGE', 'TNM Staging, Stage Classification', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\0\', 'TNM:STAGE0', 'Carcinoma in situ', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\I\', 'TNM:STAGEI', 'Cancer is localized', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\I\IA\', 'TNM:STAGEIA', 'Cancer is localized; tumor is no larger than 3 cm; No involvement of lymph nodes', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\I\IB\', 'TNM:STAGEIB', 'Cancer is localized; tumor is between 3 and 5 cm; No involvement of lymph nodes', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\II\', 'TNM:STAGEII', 'Cancer is localized, advanced within area', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\II\IIA\', 'TNM:STAGEIIA', 'Cancer is localized; tumor is greater than 3 cm; Local lymph nodes may be involved', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\II\IIB\', 'TNM:STAGEIIB', 'Cancer is localized; tumor is greater than 5 cm; Local lymph nodes may be involved; Multiple nodes may be involved', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\III\', 'TNM:STAGEIII', 'Cancer is localized, advanced within area', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\III\IIB\', 'TNM:STAGEIIIB', 'Cancer is localized;  tumor may have grown into surrounding structures; Regional lymph nodes may be involved; Multiple nodes may be involved', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\III\IIIA\', 'TNM:STAGEIIIA', 'Cancer is localized; tumor may have grown into surrounding structures; Regional lymph nodes may be involved', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\IV\', 'TNM:STAGEIV', 'Metastasized to distant lymph nodes and / organs', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Stage\Occult\', 'TNM:STAGE0', 'Cancer found in lung fluids but its location can''t be determined', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\', 'TNM:TUMOR', 'TNM Staging, Tumor Rating', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T0\', 'TNM:T0', 'No evidence of primary tumor', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T1\', 'TNM:T1', 'Tumor no greater than 3 cm', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T1\T1a\', 'TNM:T1a', 'Tumor no greater than 2 cm', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T1\T1b\', 'TNM:T1b', 'Tumor greater than 2 cm but less than 3 cm', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T2\', 'TNM:T2', 'Tumor between 3  and 7 cm', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T2\T2a\', 'TNM:T2a', 'Tumor no greater than 5 cm', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T2\T2b\', 'TNM:T2b', 'Tumor greater than 5 cm but less than 7 cm', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T3\', 'TNM:T3', 'Tumor greater than 7 cm', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\T4\', 'TNM:T4', 'Tumor grown into other areas or multiple nodules', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\Tis\', 'TNM:Tis', 'Carcinoma in situ', 'CIS; abnormal cells present but have not spread to neighboring tissue.', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Lung\TNM\Tumor\TX\', 'TNM:TX', 'Primary tumor cannot be evaluated', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Medication\Dose\', 'MED:DOSE', 'Medication Dose', '', '20110331 09:55:00.0', NULL, '20110331 09:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Medication\Frequency\', 'MED:FREQ', 'Medication Frequency', '', '20110331 09:55:00.0', NULL, '20110331 09:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Medication\Route\', 'MED:ROUTE', 'Medication Route', '', '20110331 09:55:00.0', NULL, '20110331 09:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Principal Diagnosis\', '1', 'Principal Diagnosis', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Secondary Diagnosis\', '2', 'Secondary Diagnosis', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Mild To Mod\', 'SNO:371923003', 'Severity: Mild to moderate', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Mild\', 'SNO:255604002', 'Severity: Mild', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Moderate To Severe\', 'SNO:371924009', 'Severity: Moderate to severe', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Moderate\', 'SNO:6736007', 'Severity: Moderate', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Severe\', 'SNO:24484000', 'Severity: Severe', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Severe\Fatal\', 'SNO:399166001', 'Severity: Fatal', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\Severity\Severe\Type I Hypersensitivity\', 'SNO:264774001', 'Severity: Type I Hypersensitivity', '', '20110414 00:55:00.0', NULL, '20110414 00:55:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\', 'TNM:METASTISIS', 'TNM Staging, Distant Metastisis', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\M0\', 'TNM:M0', 'TNM Staging, No distant metastasis', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\M1\', 'TNM:M1', 'TNM Staging, Distant metastasis is present', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Metastisis\MX\', 'TNM:MX', 'TNM Staging, Distant metastasis cannot be evaluated', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\', 'TNM:NODES', 'TNM Staging, Regional lymph nodes', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N0\', 'TNM:N0', 'TNM Staging, No regional lymph node involvement', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N1\', 'TNM:N1', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N2\', 'TNM:N2', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\N3\', 'TNM:N3', 'TNM Staging, Involvement of regional lymph nodes / extent of spread', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Nodes\NX\', 'TNM:NX', 'TNM Staging, Regional lymph nodes cannot be evaluated', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\', 'TNM:STAGE', 'TNM Staging, Stage Classification', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\0\', 'TNM:STAGE0', 'Carcinoma in situ', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\I\', 'TNM:STAGEI', 'Cancer is localized', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\II\', 'TNM:STAGEII', 'Cancer is localized, advanced within area', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\III\', 'TNM:STAGEIII', 'Cancer is localized, advanced within area', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Stage\IV\', 'TNM:STAGEIV', 'Metastasized to distant lymph nodes and / organs', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\', 'TNM:TUMOR', 'TNM Staging, Tumor Rating', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T0\', 'TNM:T0', 'No evidence of primary tumor', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T1\', 'TNM:T1', 'Tumor small in size', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T2\', 'TNM:T2', 'Tumor medium in size', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T3\', 'TNM:T3', 'Tumor large in size', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\T4\', 'TNM:T4', 'Tumor very large in size', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\Tis\', 'TNM:Tis', 'Carcinoma in situ', 'CIS; abnormal cells present but have not spread to neighboring tissue.', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO MODIFIER_DIMENSION(MODIFIER_PATH, MODIFIER_CD, NAME_CHAR, MODIFIER_BLOB, UPDATE_DATE, DOWNLOAD_DATE, IMPORT_DATE, SOURCESYSTEM_CD, UPLOAD_ID)
  VALUES('\TNM\Tumor\TX\', 'TNM:TX', 'Primary tumor cannot be evaluated', '', '20110415 00:10:00.0', NULL, '20110415 00:10:00.0', 'DEMO', NULL);
INSERT INTO modifier_dimension(modifier_path, modifier_cd, name_char, modifier_blob, update_date, download_date, import_date, sourcesystem_cd, UPLOAD_ID)
  VALUES('\Medication\RxSig\', 'MED:SIG', 'Rx Sig', '', '20111101 00:55:00.0', NULL, '20111101 00:55:00.0', 'DEMO', NULL);
INSERT INTO modifier_dimension(modifier_path, modifier_cd, name_char, modifier_blob, update_date, download_date, import_date, sourcesystem_cd, UPLOAD_ID)
  VALUES('\Medication\Instructions\', 'MED:INST', 'Patient Instructions', '', '20120109 00:00:00.0', NULL, '20120109 00:00:00.0', 'DEMO', NULL);
