--------------------------------------------------------
-- CLEAN QUERY TOOL SCHEMA
--------------------------------------------------------
DROP TABLE QT_PATIENT_ENC_COLLECTION;
DROP TABLE QT_PATIENT_SET_COLLECTION;
DROP TABLE QT_XML_RESULT; 
DROP TABLE QT_QUERY_RESULT_INSTANCE;
DROP TABLE QT_QUERY_INSTANCE; 
DROP TABLE QT_QUERY_STATUS;
DROP TABLE QT_QUERY_STATUS_TYPE; 
DROP TABLE QT_QUERY_RESULT_TYPE;
DROP TABLE QT_QUERY_MASTER;


--DROP INDEX
DROP INDEX QT_IDX_QM_UGID;
DROP INDEX QT_IDX_QI_UGID;