insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'(null)', N'None', N'No scheme');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'CPT4:', N'CPT4', N'Current Procedural Terminology');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|AGE:', N'DEM|AGE', N'Age of patient from demographics data');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|DATE:', N'DEM|DATE', N'Patient date of birth from demographics data');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|HISP:', N'DEM|HISP', N'Hispanic origins');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|LANGUAGE:', N'DEM|LANGUAGE', N'Primary language spoken by patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|MARITAL:', N'DEM|MARITAL', N'Marital Status of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|RACE:', N'DEM|RACE', N'Race of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|RELIGION:', N'DEM|RELIGION', N'Religion of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|SEX:', N'DEM|SEX', N'Gender of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|VITAL STATUS:', N'DEM|VITAL STATUS', N'Vital status of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DEM|ZIPCODE:', N'DEM|ZIPCODE', null);
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'DSG-NLP:', N'DSG-NLP', N'Natural Language Processing Data');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'HCPCS:', N'HCPCS', N'Healthcare Common Procedure Coding System');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'ICD10CM:', N'ICD10CM', N'ICD10 code for diagnoses');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'ICD10PCS:', N'ICD10PCS', N'ICD10 code for procedures');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'ICD9CM:', N'ICD9CM', N'ICD9 code for diagnoses and procedures');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'ICD9PROC:', N'ICD9PROC', N'ICD9 code for procedures');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'LOINC:', N'LOINC', N'Lab codes');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'NDC:', N'NDC', N'National Drug Code');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'NUI:', N'NDF-RT', N'NDF-RT VA Drug Classification');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'RXNORM:', N'RXNORM', N'RxNorm');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values (N'UMLS:', N'UMLS', N'United Medical Language System');
