insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('(null)', 'None', 'No scheme');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('CPT4:', 'CPT4', 'Current Procedural Terminology');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|AGE:', 'DEM|AGE', 'Age of patient from demographics data');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|DATE:', 'DEM|DATE', 'Patient date of birth from demographics data');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|HISP:', 'DEM|HISP', 'Hispanic origins');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|LANGUAGE:', 'DEM|LANGUAGE', 'Primary language spoken by patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|MARITAL:', 'DEM|MARITAL', 'Marital Status of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|RACE:', 'DEM|RACE', 'Race of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|RELIGION:', 'DEM|RELIGION', 'Religion of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|SEX:', 'DEM|SEX', 'Gender of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|VITAL STATUS:', 'DEM|VITAL STATUS', 'Vital status of patient');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DEM|ZIPCODE:', 'DEM|ZIPCODE', null);
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('DSG-NLP:', 'DSG-NLP', 'Natural Language Processing Data');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('HCPCS:', 'HCPCS', 'Healthcare Common Procedure Coding System');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('ICD10CM:', 'ICD10CM', 'ICD10 code for diagnoses');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('ICD10PCS:', 'ICD10PCS', 'ICD10 code for procedures');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('ICD9CM:', 'ICD9CM', 'ICD9 code for diagnoses and procedures');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('ICD9PROC:', 'ICD9PROC', 'ICD9 code for procedures');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('LOINC:', 'LOINC', 'Lab codes');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('NDC:', 'NDC', 'National Drug Code');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('NUI:', 'NDF-RT', 'NDF-RT VA Drug Classification');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('RXNORM:', 'RXNORM', 'RxNorm');
insert into SCHEMES (C_KEY, C_NAME, C_DESCRIPTION) values ('UMLS:', 'UMLS', 'United Medical Language System');
