CREATE or replace TRIGGER PM_PROJECT_REQUEST_INC
	BEFORE INSERT
	ON PM_PROJECT_REQUEST
	FOR EACH ROW
	BEGIN
	SELECT PM_PARAMS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER PM_CELL_PARAMS_INC
	BEFORE INSERT
	ON PM_CELL_PARAMS
	FOR EACH ROW
	BEGIN
	SELECT PM_PARAMS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER PM_GLOBAL_PARAMS_INC
	BEFORE INSERT
	ON PM_GLOBAL_PARAMS
	REFERENCING NEW AS NEW
	FOR EACH ROW
	BEGIN
	SELECT PM_PARAMS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER PM_HIVE_PARAMS_INC
	BEFORE INSERT
	ON PM_HIVE_PARAMS
	FOR EACH ROW
	BEGIN
	SELECT PM_PARAMS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER PM_PROJECT_PARAMS_INC
	BEFORE INSERT
	ON PM_PROJECT_PARAMS
	FOR EACH ROW
	BEGIN
	SELECT PM_PARAMS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER PM_PROJECT_USER_PARAMS_INC
	BEFORE INSERT
	ON PM_PROJECT_USER_PARAMS
	FOR EACH ROW
	BEGIN
	SELECT PM_PARAMS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER PM_USER_PARAMS_INC
	BEFORE INSERT
	ON PM_USER_PARAMS
	FOR EACH ROW
	BEGIN
	SELECT PM_PARAMS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
